/// A drill that ships with the app.
///
/// The competitive gap this closes: a blank board asks the coach to do the
/// work before the app is worth anything. A drill is a board plus the reason
/// to run it, so the first session can be planned in the car park.
///
/// The board is the same JSON a saved tactic uses, so loading one is exactly
/// loading a tactic — animation, phases and all — and the coach can edit it
/// from there. Content lives in `assets/drills/<sport>.json`, generated by
/// tools/gen_drills.py; nothing here is user data.
class Drill {
  final String id;
  final DrillCategory category;

  /// Rough session length, and how many players it needs on the pitch. Both
  /// are what a coach actually filters on when planning a Tuesday.
  final int minutes;
  final int players;

  /// Locale code -> text. English is always present and is the fallback: a
  /// missing translation must show the drill, not hide it.
  final Map<String, String> name;
  final Map<String, String> note;

  /// The board itself, in TacticsState's JSON shape.
  final Map<String, dynamic> board;

  const Drill({
    required this.id,
    required this.category,
    required this.minutes,
    required this.players,
    required this.name,
    required this.note,
    required this.board,
  });

  factory Drill.fromJson(Map<String, dynamic> json) => Drill(
        id: json['id'] as String,
        category: DrillCategory.parse(json['category'] as String?),
        minutes: (json['minutes'] as num?)?.toInt() ?? 0,
        players: (json['players'] as num?)?.toInt() ?? 0,
        name: Map<String, String>.from(json['name'] as Map),
        note: Map<String, String>.from(json['note'] as Map? ?? const {}),
        board: Map<String, dynamic>.from(json['board'] as Map),
      );

  /// Best text for [locale] (e.g. 'zh-CN'), falling back to the language
  /// ('zh'), then English. A drill without a translation still shows up.
  static String _pick(Map<String, String> texts, String locale) {
    if (texts.containsKey(locale)) return texts[locale]!;
    final lang = locale.split(RegExp(r'[-_]')).first;
    for (final key in texts.keys) {
      if (key.split(RegExp(r'[-_]')).first == lang) return texts[key]!;
    }
    return texts['en'] ?? texts.values.firstOrNull ?? '';
  }

  String localizedName(String locale) => _pick(name, locale);

  String localizedNote(String locale) => _pick(note, locale);
}

enum DrillCategory {
  warmup,
  possession,
  attacking,
  finishing,
  defending,
  setpiece,
  ssg;

  static DrillCategory parse(String? raw) => DrillCategory.values.firstWhere(
        (c) => c.name == raw,
        orElse: () => DrillCategory.possession,
      );

  /// Translation key for the category chip.
  String get labelKey => 'drill_cat_$name';
}

extension _FirstOrNull<T> on Iterable<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
