/// A drill that ships with the app.
///
/// The competitive gap this closes: a blank board asks the coach to do the
/// work before the app is worth anything. A drill is a board plus the reason
/// to run it, so the first session can be planned in the car park.
///
/// The board is the same JSON a saved tactic uses, so loading one is exactly
/// loading a tactic — animation, phases and all — and the coach can edit it
/// from there. Content lives in `assets/drills/<sport>.json`, generated by
/// tools/gen_drills.py; nothing here is user data.
class Drill {
  final String id;
  final DrillCategory category;

  /// Rough session length, and how many players it needs on the pitch. Both
  /// are what a coach actually filters on when planning a Tuesday.
  final int minutes;
  final int players;

  /// Locale code -> text. English is always present and is the fallback: a
  /// missing translation must show the drill, not hide it.
  final Map<String, String> name;
  final Map<String, String> note;

  /// The board itself, in TacticsState's JSON shape.
  final Map<String, dynamic> board;

  /// This drill deliberately puts someone off the playing surface — a
  /// throw-in taker stands behind the touchline. Only used by checks.
  final bool offSurface;

  /// In the free tier. The free set spans every category on purpose — a coach
  /// can run a whole session on it — because the subscription has to be worth
  /// buying on top of something useful, not instead of it.
  final bool free;

  const Drill({
    required this.id,
    required this.category,
    required this.minutes,
    required this.players,
    required this.name,
    required this.note,
    required this.board,
    this.free = false,
    this.offSurface = false,
  });

  factory Drill.fromJson(Map<String, dynamic> json) => Drill(
        id: json['id'] as String,
        category: DrillCategory.parse(json['category'] as String?),
        minutes: (json['minutes'] as num?)?.toInt() ?? 0,
        players: (json['players'] as num?)?.toInt() ?? 0,
        name: Map<String, String>.from(json['name'] as Map),
        note: Map<String, String>.from(json['note'] as Map? ?? const {}),
        board: Map<String, dynamic>.from(json['board'] as Map),
        free: json['free'] as bool? ?? false,
        offSurface: json['offSurface'] as bool? ?? false,
      );

  /// Best text for [locale] (e.g. 'zh-CN'), falling back to the language
  /// ('zh'), then English. A drill without a translation still shows up.
  static String _pick(Map<String, String> texts, String locale) {
    if (texts.containsKey(locale)) return texts[locale]!;
    final lang = locale.split(RegExp(r'[-_]')).first;
    for (final key in texts.keys) {
      if (key.split(RegExp(r'[-_]')).first == lang) return texts[key]!;
    }
    return texts['en'] ?? texts.values.firstOrNull ?? '';
  }

  String localizedName(String locale) => _pick(name, locale);

  String localizedNote(String locale) => _pick(note, locale);
}

/// Which words a sport's coach uses for the seven categories.
///
/// A session is built the same way everywhere — warm up, work the ball, work
/// the goal, play a game — so the categories themselves are shared. The words
/// are not: "possession" means nothing in badminton, where the same category
/// is the rally, and "set piece" there is just the serve. Only the words that
/// are actually wrong are overridden; the rest fall back to the shared key.
enum DrillVocabulary {
  /// Invasion sports. The default labels were written for these.
  pitch,

  /// Racket and net sports — a rally, a serve, and match play.
  net,

  /// Baseball, which shares almost none of the vocabulary.
  diamond,
}

enum DrillCategory {
  warmup,
  possession,
  attacking,
  finishing,
  defending,
  setpiece,
  ssg;

  static DrillCategory parse(String? raw) => DrillCategory.values.firstWhere(
        (c) => c.name == raw,
        orElse: () => DrillCategory.possession,
      );

  /// Translation key for the category chip, in the sport's own words.
  ///
  /// Falls back to the shared key wherever a sport has no better word, which
  /// is most of them — "Warm-up" and "Defending" need no translating twice.
  String labelKeyFor(DrillVocabulary vocabulary) {
    const overrides = <DrillVocabulary, Set<DrillCategory>>{
      DrillVocabulary.net: {
        DrillCategory.possession,   // the rally
        DrillCategory.setpiece,     // the serve
        DrillCategory.ssg,          // match play
      },
      DrillVocabulary.diamond: {
        DrillCategory.possession,   // fielding
        DrillCategory.attacking,    // baserunning
        DrillCategory.finishing,    // scoring
        DrillCategory.setpiece,     // holding the runner
        DrillCategory.ssg,          // scrimmage
      },
    };
    if (overrides[vocabulary]?.contains(this) ?? false) {
      return 'drill_cat_${name}_${vocabulary.name}';
    }
    return 'drill_cat_$name';
  }

  /// The shared key, for anywhere a sport is not in hand.
  String get labelKey => 'drill_cat_$name';
}

extension _FirstOrNull<T> on Iterable<T> {
  T? get firstOrNull => isEmpty ? null : first;
}
