"""Conditioning without the ball, for every sport but soccer.

Soccer has its own eight in soccer_fitness.py. This is the same idea for
the other fourteen: the running, sliding, jumping and recovering a match
in that sport asks for, written the way that sport's coach runs it — a
basketball 17, a rugby bronco, a water polo eggbeater set, a badminton
six-corner shadow. No ball on any of them; each says how many, how long
and how much rest, because a conditioning drill without a dose is a
picture of somebody running.

The texts a drill shares with the same drill in another sport are written
once here; everything that is really about the sport — where the lines
are, what the equipment marks, how the group rotates — is authored per
sport below.
"""
from .engine import Drill, M, P


def _t(en, zh, zht, ja, ko, es, fr, id_, ms, th, vi):
    return {"en": en, "en-GB": en, "zh-CN": zh, "zh-TW": zht, "ja-JP": ja,
            "ko-KR": ko, "es-ES": es, "fr-FR": fr, "id-ID": id_, "ms-MY": ms,
            "th-TH": th, "vi-VN": vi}


def _s(en, zh, zht):
    """Set-up, equipment and continuation lines: four locales and English
    as the fallback for the rest, the same as every hand-written setup."""
    return {"en": en, "en-GB": en, "zh-CN": zh, "zh-TW": zht}


# ══ what every conditioning drill is for ═════════════════════════════════
PURPOSE_COURT = _t(
    "Fitness without the ball: accelerate, change direction, and do it again tired — the movement the sport asks for, when the match is decided by who can still produce it.",
    "无球体能：加速、变向、疲劳下还能重复——这项运动要求的移动能力，比赛往往由谁还做得出来决定。",
    "無球體能：加速、變向、疲勞下還能重複——這項運動要求的移動能力，比賽往往由誰還做得出來決定。",
    "ボールなしのフィジカル：加速、方向転換、疲れてももう一度——競技が求める動きで、勝負はまだそれができる側が決める。",
    "볼 없는 체력: 가속, 방향 전환, 지쳐도 한 번 더 — 종목이 요구하는 움직임이며, 승부는 아직 그것을 해내는 쪽이 정한다.",
    "Físico sin balón: acelerar, cambiar de dirección y repetirlo cansado; el movimiento que pide el deporte, y el partido lo decide quien todavía puede producirlo.",
    "Physique sans ballon : accélérer, changer de direction et recommencer fatigué — le mouvement qu'exige le sport, et le match revient à qui peut encore le produire.",
    "Fisik tanpa bola: berakselerasi, ganti arah, dan mengulanginya saat lelah — gerak yang dituntut olahraga ini.",
    "Fizikal tanpa bola: memecut, tukar arah, dan mengulanginya ketika penat — pergerakan yang dituntut sukan ini.",
    "ฟิตเนสไร้ลูก: เร่ง เปลี่ยนทิศ และทำซ้ำตอนเหนื่อย คือการเคลื่อนที่ที่กีฬานี้ต้องการ",
    "Thể lực không bóng: tăng tốc, đổi hướng và lặp lại khi mệt — chuyển động môn này đòi hỏi, và trận đấu thuộc về bên còn làm được.")

PURPOSE_WATER = _t(
    "Fitness in the water: legs that hold you up, a sprint that still arrives in the fourth quarter, and the recovery between them.",
    "水中体能：撑得住身体的腿、第四节还冲得动的速度，以及两者之间的恢复。",
    "水中體能：撐得住身體的腿、第四節還衝得動的速度，以及兩者之間的恢復。",
    "水中のフィジカル：体を支える脚、第4クォーターでも届くスプリント、そしてその間の回復。",
    "물속 체력: 몸을 떠받치는 다리, 4쿼터에도 도달하는 스프린트, 그리고 그 사이의 회복.",
    "Físico en el agua: piernas que te sostienen, un sprint que todavía llega en el último cuarto y la recuperación entre ambos.",
    "Physique dans l'eau : des jambes qui te portent, un sprint qui arrive encore au dernier quart-temps, et la récupération entre les deux.",
    "Fisik di air: kaki yang menopang, sprint yang masih sampai di kuarter keempat, dan pemulihan di antaranya.",
    "Fizikal dalam air: kaki yang menyokong, pecutan yang masih sampai pada suku keempat, dan pemulihan antara keduanya.",
    "ฟิตเนสในน้ำ: ขาที่พยุงตัวได้ สปรินต์ที่ยังถึงในควอเตอร์สี่ และการฟื้นตัวระหว่างนั้น",
    "Thể lực dưới nước: đôi chân giữ được người, cú bơi nước rút vẫn tới ở hiệp bốn, và sự hồi phục giữa hai điều đó.")

PURPOSE_SAND = _t(
    "Fitness in the sand: every step costs more than it does on a court, so the legs are built and the landings are safe — and the first three steps are the whole game.",
    "沙地体能：每一步都比硬地费力，练的是腿也是落地的安全——而这项运动拼的就是头三步。",
    "沙地體能：每一步都比硬地費力，練的是腿也是落地的安全——而這項運動拼的就是頭三步。",
    "砂上のフィジカル：一歩がコートより重く、脚も着地の安全も鍛えられる——そしてこの競技は最初の3歩で決まる。",
    "모래에서의 체력: 한 걸음이 코트보다 무겁다. 다리도 착지의 안전도 함께 만들어지며, 이 종목은 첫 세 걸음이 전부다.",
    "Físico en la arena: cada paso cuesta más que en pista, así que se construyen las piernas y se aseguran las caídas; y en este deporte todo son los tres primeros pasos.",
    "Physique sur le sable : chaque appui coûte plus que sur un terrain dur, on construit les jambes et on sécurise les réceptions — et tout se joue sur les trois premiers pas.",
    "Fisik di pasir: setiap langkah lebih berat daripada di lapangan keras, kaki terbentuk dan pendaratan jadi aman.",
    "Fizikal di pasir: setiap langkah lebih berat daripada di gelanggang keras, kaki terbentuk dan pendaratan jadi selamat.",
    "ฟิตเนสบนทราย: ทุกก้าวหนักกว่าบนคอร์ต สร้างขาและลงพื้นอย่างปลอดภัย และกีฬานี้วัดกันที่สามก้าวแรก",
    "Thể lực trên cát: mỗi bước nặng hơn trên sân cứng, vừa xây chân vừa an toàn khi tiếp đất — và môn này quyết ở ba bước đầu.")


# ══ notes shared by the same drill in several sports ══════════════════════
SHUTTLE_NAME = _t("Line shuttle", "折返跑 触线", "折返跑 觸線", "シャトルラン", "셔틀런",
                  "Ida y vuelta a las líneas", "Navettes sur les lignes", "Lari bolak-balik garis",
                  "Lari ulang-alik garisan", "วิ่งกลับตัวแตะเส้น", "Chạy con thoi chạm vạch")
SHUTTLE_NOTE = _t(
    "Touch every line with the hand and push off the outside foot — the seconds are lost in the turn, not in the running.",
    "每条线都用手触到，蹬地用外侧脚——时间丢在转身上，不是丢在跑上。",
    "每條線都用手觸到，蹬地用外側腳——時間丟在轉身上，不是丟在跑上。",
    "どのラインも手でタッチし、外側の足で蹴る——タイムはターンで失われ、走りでは失われない。",
    "모든 선을 손으로 짚고 바깥 발로 밀어낸다 — 시간은 달리기가 아니라 턴에서 사라진다.",
    "Toca cada línea con la mano y empuja con el pie exterior: los segundos se pierden en el giro, no corriendo.",
    "Touche chaque ligne de la main et pousse sur le pied extérieur : les secondes se perdent dans le demi-tour, pas dans la course.",
    "Sentuh setiap garis dengan tangan dan dorong dengan kaki luar — detik hilang di putaran, bukan di larinya.",
    "Sentuh setiap garisan dengan tangan dan tolak dengan kaki luar — saat hilang pada pusingan, bukan pada larian.",
    "แตะทุกเส้นด้วยมือและดันด้วยเท้าด้านนอก เวลาหายไปตอนกลับตัว ไม่ใช่ตอนวิ่ง",
    "Chạm mỗi vạch bằng tay và đạp bằng chân ngoài — thời gian mất ở chỗ quay, không phải ở lúc chạy.")

LATERAL_NAME = _t("Lateral shuffle", "横向滑步", "橫向滑步", "サイドステップ", "사이드 스텝",
                  "Desplazamientos laterales", "Pas chassés latéraux", "Geser menyamping",
                  "Gerak sisi", "สไลด์ข้าง", "Trượt ngang")
LATERAL_NOTE = _t(
    "Feet never cross and the head never bobs: stay low the whole way, and the last step out is as wide as the first.",
    "脚不交叉，头不上下起伏：全程保持低重心，最后一步要和第一步一样大。",
    "腳不交叉，頭不上下起伏：全程保持低重心，最後一步要和第一步一樣大。",
    "足は交差させず、頭は上下させない：最後まで低く、最後の一歩も最初と同じ幅で。",
    "발은 교차하지 않고 머리는 위아래로 흔들리지 않는다: 끝까지 낮게, 마지막 한 걸음도 첫 걸음만큼 넓게.",
    "Los pies no se cruzan y la cabeza no sube y baja: mantente bajo todo el rato y el último paso es tan amplio como el primero.",
    "Les pieds ne se croisent pas et la tête ne monte pas : reste bas jusqu'au bout, le dernier appui aussi large que le premier.",
    "Kaki tidak menyilang dan kepala tidak naik-turun: tetap rendah sampai akhir, langkah terakhir selebar yang pertama.",
    "Kaki tidak bersilang dan kepala tidak naik turun: kekal rendah hingga akhir, langkah terakhir selebar yang pertama.",
    "เท้าไม่ไขว้ หัวไม่ขึ้นลง ย่อตัวต่ำตลอด ก้าวสุดท้ายกว้างเท่าก้าวแรก",
    "Chân không bắt chéo, đầu không nhấp nhô: giữ thấp suốt, bước cuối rộng như bước đầu.")

REPEAT_NAME = _t("Repeat sprints", "反复冲刺", "反覆衝刺", "反復スプリント", "반복 스프린트",
                 "Sprints repetidos", "Sprints répétés", "Sprint berulang",
                 "Pecutan berulang", "สปรินต์ซ้ำ", "Chạy nước rút lặp lại")
REPEAT_NOTE = _t(
    "The set is judged on the last rep, not the first: if the sixth is much slower than the second, the rest is too short or the effort was not honest.",
    "一组的成色看最后一趟，不看第一趟：如果第六趟比第二趟慢很多，要么休息不够，要么之前没真跑。",
    "一組的成色看最後一趟，不看第一趟：如果第六趟比第二趟慢很多，要麼休息不夠，要麼之前沒真跑。",
    "セットは最初ではなく最後の1本で評価する：6本目が2本目よりかなり遅いなら、休息が短いか、手を抜いていたかだ。",
    "세트는 첫 회차가 아니라 마지막 회차로 평가한다: 여섯 번째가 두 번째보다 훨씬 느리면 휴식이 짧았거나 앞에서 힘을 아꼈던 것이다.",
    "La serie se juzga por la última repetición, no por la primera: si la sexta es mucho más lenta que la segunda, el descanso es corto o el esfuerzo no fue honesto.",
    "La série se juge à la dernière répétition, pas à la première : si la sixième est bien plus lente que la deuxième, la récupération est trop courte ou l'effort n'était pas sincère.",
    "Satu set dinilai dari ulangan terakhir, bukan yang pertama: kalau yang keenam jauh lebih lambat, istirahatnya kurang atau usahanya tidak jujur.",
    "Satu set dinilai dari ulangan terakhir, bukan yang pertama: jika keenam jauh lebih perlahan, rehatnya kurang atau usahanya tidak jujur.",
    "เซ็ตหนึ่งวัดกันที่รอบสุดท้าย ไม่ใช่รอบแรก ถ้ารอบหกช้ากว่ารอบสองมาก แปลว่าพักน้อยไปหรือก่อนหน้านี้ไม่ได้ทุ่มจริง",
    "Một hiệp được đánh giá ở lượt cuối, không phải lượt đầu: nếu lượt sáu chậm hơn lượt hai nhiều thì nghỉ chưa đủ hoặc trước đó chưa gắng thật.")

JUMP_NAME = _t("Jump series", "连续起跳", "連續起跳", "連続ジャンプ", "연속 점프",
               "Serie de saltos", "Série de sauts", "Seri lompatan",
               "Siri lompatan", "ชุดกระโดด", "Chuỗi bật nhảy")
JUMP_NOTE = _t(
    "Reach the same height on the last jump as on the first; the moment the height drops the set is over, however many are left — height is the quality being trained.",
    "最后一跳要和第一跳一样高；高度一掉就停，不管还剩几个——练的就是高度。",
    "最後一跳要和第一跳一樣高；高度一掉就停，不管還剩幾個——練的就是高度。",
    "最後の1本も1本目と同じ高さまで跳ぶ。高さが落ちた時点で、残りが何本でもそのセットは終わり——鍛えているのは高さだ。",
    "마지막 점프도 첫 점프와 같은 높이로. 높이가 떨어지는 순간 몇 개가 남았든 세트는 끝이다 — 훈련하는 것은 높이다.",
    "Alcanza la misma altura en el último salto que en el primero; en cuanto baja la altura, la serie se acaba, queden los que queden: lo que se entrena es la altura.",
    "Atteins la même hauteur au dernier saut qu'au premier ; dès que la hauteur baisse, la série est finie, quel qu'en soit le reste — c'est la hauteur que l'on travaille.",
    "Capai tinggi yang sama pada lompatan terakhir seperti yang pertama; begitu tingginya turun, set selesai.",
    "Capai ketinggian yang sama pada lompatan terakhir seperti yang pertama; sebaik ketinggian turun, set tamat.",
    "กระโดดครั้งสุดท้ายให้สูงเท่าครั้งแรก พอความสูงตกให้จบเซ็ตทันที เพราะสิ่งที่ฝึกคือความสูง",
    "Lần bật cuối phải cao bằng lần đầu; ngay khi độ cao giảm là kết thúc hiệp, còn bao nhiêu cũng bỏ — thứ đang tập là độ cao.")

SHADOW_NAME = _t("Shadow footwork", "影子步法", "影子步法", "シャドー・フットワーク", "섀도 풋워크",
                 "Desplazamientos en sombra", "Déplacements à vide", "Footwork bayangan",
                 "Kerja kaki bayangan", "ฟุตเวิร์กเงา", "Di chuyển không bóng")
SHADOW_NOTE = _t(
    "Play the stroke at every corner — a footwork drill in which nobody swings is a running drill, and the racket arm is half of the balance.",
    "每到一个点都要把挥拍动作做出来——不挥拍的步法练习只是跑步，而持拍手是平衡的一半。",
    "每到一個點都要把揮拍動作做出來——不揮拍的步法練習只是跑步，而持拍手是平衡的一半。",
    "各コーナーで必ずスイングする——振らないフットワークはただの走りで、ラケット側の腕はバランスの半分だ。",
    "각 코너마다 스윙을 한다 — 스윙 없는 풋워크는 그냥 달리기이고, 라켓 든 팔이 균형의 절반이다.",
    "Golpea en cada esquina: un ejercicio de pies en el que nadie golpea es correr, y el brazo de la raqueta es la mitad del equilibrio.",
    "Joue le coup à chaque coin — un travail de jambes sans frappe n'est que de la course, et le bras de la raquette fait la moitié de l'équilibre.",
    "Lakukan ayunan di tiap sudut — latihan kaki tanpa ayunan hanyalah lari.",
    "Lakukan ayunan di setiap sudut — latihan kaki tanpa ayunan hanyalah larian.",
    "ตีทุกมุม การฝึกฟุตเวิร์กที่ไม่สวิงคือการวิ่งเฉย ๆ และแขนที่ถือไม้คือครึ่งหนึ่งของการทรงตัว",
    "Vung vợt ở mọi góc — bài chân mà không vung là bài chạy, và tay cầm vợt là một nửa của thăng bằng.")

SAND_NAME = _t("Sand sprints", "沙地冲刺", "沙地衝刺", "砂上スプリント", "모래 스프린트",
               "Sprints en arena", "Sprints sur sable", "Sprint di pasir",
               "Pecutan di pasir", "สปรินต์บนทราย", "Chạy nước rút trên cát")
SAND_NOTE = _t(
    "Short steps and high knees — the sand takes the stride length away, so the speed has to come from turning the legs over faster.",
    "小步、高抬腿——沙子会把步幅吃掉，速度只能靠步频提上去。",
    "小步、高抬腿——沙子會把步幅吃掉，速度只能靠步頻提上去。",
    "歩幅は小さく、膝は高く——砂はストライドを奪うので、速さは回転の速さで出すしかない。",
    "보폭은 짧게, 무릎은 높게 — 모래가 보폭을 먹어버리니 속도는 회전수로 내야 한다.",
    "Pasos cortos y rodillas altas: la arena se lleva la zancada, así que la velocidad sale de mover las piernas más rápido.",
    "Petites foulées, genoux hauts : le sable mange l'amplitude, la vitesse vient donc de la fréquence.",
    "Langkah pendek dan lutut tinggi — pasir memakan panjang langkah, jadi kecepatan datang dari frekuensi.",
    "Langkah pendek dan lutut tinggi — pasir memakan panjang langkah, jadi kelajuan datang dari kekerapan.",
    "ก้าวสั้นและยกเข่าสูง ทรายกินความยาวก้าว ความเร็วจึงต้องมาจากความถี่",
    "Bước ngắn và nâng cao gối — cát lấy mất sải chân, tốc độ phải đến từ tần số.")


# ══ basketball ═══════════════════════════════════════════════════════════
def _basketball():
    return [
        Drill(
            id="bkfit_suicides", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, free=True,
            name=_t("Suicides (17s)", "折返跑 17 次", "折返跑 17 次", "スーサイド（17本）",
                    "수어사이드 (17)", "Suicidios (17)", "Navettes 17", "Lari suicide (17)",
                    "Larian suicide (17)", "วิ่งซุยไซด์ 17", "Chạy con thoi 17"),
            note=_t("Every line is touched with the hand, and the far baseline is a baseline, not the three-point line you decided was close enough at rep four.",
                    "每条线都用手触到；远端底线就是底线，不是你跑到第四趟时觉得差不多的三分线。",
                    "每條線都用手觸到；遠端底線就是底線，不是你跑到第四趟時覺得差不多的三分線。",
                    "すべてのラインを手でタッチ。遠いエンドラインはエンドラインであって、4本目で「これで十分」と決めた3Pラインではない。",
                    "모든 선을 손으로 짚는다. 먼 쪽 엔드라인은 엔드라인이지, 네 번째 회차에서 적당하다고 정한 3점 라인이 아니다.",
                    "Cada línea se toca con la mano, y la línea de fondo lejana es la línea de fondo, no el triple que en la cuarta repetición te pareció suficiente.",
                    "Chaque ligne se touche à la main, et la ligne de fond opposée est bien la ligne de fond, pas la ligne à trois points jugée suffisante au quatrième aller.",
                    "Setiap garis disentuh dengan tangan, dan garis belakang jauh tetap garis belakang.",
                    "Setiap garisan disentuh dengan tangan, dan garisan belakang jauh tetap garisan belakang.",
                    "แตะทุกเส้นด้วยมือ และเส้นหลังฝั่งไกลคือเส้นหลัง ไม่ใช่เส้นสามแต้มที่คุณคิดว่าพอแล้วตอนรอบสี่",
                    "Chạm mọi vạch bằng tay, và vạch cuối sân xa là vạch cuối sân, không phải vạch ba điểm bạn cho là đủ ở lượt thứ tư."),
            home=[P(0.50, 0.96, "A",
                    moves=[(0.50, 0.80, 0), (0.50, 0.96, 1), (0.50, 0.50, 2), (0.50, 0.96, 3),
                           (0.50, 0.21, 4), (0.50, 0.96, 5), (0.50, 0.05, 6), (0.50, 0.96, 7)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                         4: "sprint", 5: "turn_back", 6: "sprint", 7: "turn_back"})],
            setup=_s("the whole court, the runner on one baseline; the court's own lines are the targets",
                     "整片球场，跑者站在一侧底线，球场自带的线就是目标",
                     "整片球場，跑者站在一側底線，球場自帶的線就是目標"),
            gear=_s("no equipment: the near free-throw line, halfway, the far free-throw line and the far baseline are the four turns, each touched with the hand",
                    "不需要器材：近端罚球线、中线、远端罚球线、远端底线是四个折返点，每个都用手触线",
                    "不需要器材：近端罰球線、中線、遠端罰球線、遠端底線是四個折返點，每個都用手觸線"),
            flow=_s("Four out-and-backs is one suicide, inside 33 seconds for a senior team; walk 60 seconds and go again. Six suicides, then five minutes off your feet.",
                    "四个折返为一趟，成年队要求 33 秒内完成；走 60 秒再来。做 6 趟，然后坐下休息 5 分钟。",
                    "四個折返為一趟，成年隊要求 33 秒內完成；走 60 秒再來。做 6 趟，然後坐下休息 5 分鐘。"),
        ),
        Drill(
            id="bkfit_defensive_slide", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.24, 0.94, "A",
                    moves=[(0.68, 0.78, 0), (0.24, 0.62, 1), (0.68, 0.46, 2), (0.24, 0.30, 3),
                           (0.50, 0.94, 4)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle", 4: "jog"})],
            markers=[M(0.20, 0.94), M(0.72, 0.78), M(0.20, 0.62), M(0.72, 0.46), M(0.20, 0.30)],
            setup=_s("five cones in a zig-zag up the court, each about 5 m across and 4 m on from the last; the defender starts on the first",
                     "五个锥标在半场内呈之字形摆开，每一个比上一个横向约 5 米、纵向约 4 米，防守者站在第一个锥标上",
                     "五個錐標在半場內呈之字形擺開，每一個比上一個橫向約 5 米、縱向約 4 米，防守者站在第一個錐標上"),
            gear=_s("the cones are the turning points of the zig-zag: slide to each one, plant the outside foot and change direction without standing up",
                    "锥标是之字形的转折点：滑到每个锥标，用外侧脚蹬地换向，中间不许站起来",
                    "錐標是之字形的轉折點：滑到每個錐標，用外側腳蹬地換向，中間不許站起來"),
            flow=_s("One length of the zig-zag, jog back down the sideline, and the next defender goes; six lengths each, two sets, two minutes between sets.",
                    "之字形滑一趟，沿边线慢跑回来，下一人出发；每人 6 趟一组，做 2 组，组间休息 2 分钟。",
                    "之字形滑一趟，沿邊線慢跑回來，下一人出發；每人 6 趟一組，做 2 組，組間休息 2 分鐘。"),
        ),
        Drill(
            id="bkfit_lane_agility", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("Lane agility", "禁区绕框敏捷", "禁區繞框敏捷", "レーンアジリティ", "레인 어질리티",
                    "Agilidad en la zona", "Agilité dans la raquette", "Kelincahan area terlarang",
                    "Ketangkasan kawasan", "อไจลิตี้รอบเขตโทษ", "Nhanh nhẹn quanh khu 3 giây"),
            note=_t("Four movements, one lap: sprint, slide, backpedal, slide. The corner is the drill — get the hips round it without a wasted step.",
                    "一圈四种移动：冲刺、滑步、后退跑、滑步。转角才是练习内容——转胯要干净，不多余一步。",
                    "一圈四種移動：衝刺、滑步、後退跑、滑步。轉角才是練習內容——轉胯要乾淨，不多餘一步。",
                    "1周に4つの動き：ダッシュ、スライド、バックペダル、スライド。コーナーこそがドリルだ——無駄な一歩なしで腰を回す。",
                    "한 바퀴에 네 가지 동작: 질주, 슬라이드, 백페달, 슬라이드. 코너가 곧 훈련이다 — 헛걸음 없이 골반을 돌린다.",
                    "Cuatro movimientos, una vuelta: sprint, desplazamiento, atrás, desplazamiento. La esquina es el ejercicio: gira las caderas sin un paso de más.",
                    "Quatre déplacements, un tour : sprint, pas chassés, course arrière, pas chassés. Le coin est l'exercice : tourner les hanches sans un appui de trop.",
                    "Empat gerakan, satu putaran: sprint, geser, mundur, geser. Sudutnya adalah latihannya.",
                    "Empat pergerakan, satu pusingan: pecut, geser, undur, geser. Sudutnya ialah latihannya.",
                    "หนึ่งรอบสี่การเคลื่อนที่: สปรินต์ สไลด์ ถอยหลัง สไลด์ มุมคือแบบฝึก หมุนสะโพกโดยไม่เสียก้าว",
                    "Bốn kiểu di chuyển trong một vòng: nước rút, trượt ngang, chạy lùi, trượt ngang. Góc mới là bài tập — xoay hông gọn, không thừa bước."),
            home=[P(0.37, 0.95, "A",
                    moves=[(0.37, 0.80, 0), (0.63, 0.80, 1), (0.63, 0.95, 2), (0.37, 0.95, 3)],
                    why={0: "sprint", 1: "shuffle", 2: "backpedal", 3: "shuffle"})],
            markers=[M(0.34, 0.97), M(0.34, 0.78), M(0.66, 0.78), M(0.66, 0.97)],
            setup=_s("four cones on the corners of the lane, the runner on the bottom-left one",
                     "四个锥标摆在禁区（油漆区）的四个角，跑者站在左下角的锥标上",
                     "四個錐標擺在禁區（油漆區）的四個角，跑者站在左下角的錐標上"),
            gear=_s("the cones are the four corners: sprint up the left side, slide across the top, backpedal down the right, slide back along the baseline",
                    "四个锥标是四个角：沿左侧冲刺向上，沿顶端滑步横移，沿右侧后退跑，再沿底线滑步回来",
                    "四個錐標是四個角：沿左側衝刺向上，沿頂端滑步橫移，沿右側後退跑，再沿底線滑步回來"),
            flow=_s("Two laps one way, two the other, and time the pair; rest 45 seconds and the next player goes. Four rounds each.",
                    "顺时针两圈、逆时针两圈，计一次时；休息 45 秒换下一人。每人做 4 轮。",
                    "順時針兩圈、逆時針兩圈，計一次時；休息 45 秒換下一人。每人做 4 輪。"),
        ),
    ]


# ══ volleyball ═══════════════════════════════════════════════════════════
def _volleyball():
    return [
        Drill(
            id="vbfit_approach_jumps", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, free=True,
            name=_t("Approach jumps", "连续助跑起跳", "連續助跑起跳", "助走ジャンプ連続", "연속 도움닫기 점프",
                    "Saltos con carrera", "Sauts avec course d'élan", "Lompat dengan awalan",
                    "Lompatan dengan langkah awalan", "กระโดดพร้อมสเต็ปเข้า", "Bật nhảy có đà"),
            note=_t("Four steps every time, the last two fast and low, and land on both feet — a jump you cannot land is a jump you cannot repeat.",
                    "每次都是四步助跑，最后两步快而低，双脚落地——落不好的起跳就没法连续做。",
                    "每次都是四步助跑，最後兩步快而低，雙腳落地——落不好的起跳就沒法連續做。",
                    "毎回4歩の助走、最後の2歩は速く低く、両足で着地する——着地できないジャンプは繰り返せないジャンプだ。",
                    "매번 네 걸음 도움닫기, 마지막 두 걸음은 빠르고 낮게, 두 발로 착지한다 — 착지하지 못하는 점프는 반복할 수 없는 점프다.",
                    "Cuatro pasos siempre, los dos últimos rápidos y bajos, y se aterriza con los dos pies: un salto que no puedes aterrizar es un salto que no puedes repetir.",
                    "Quatre appuis à chaque fois, les deux derniers rapides et bas, réception sur deux pieds : un saut que l'on ne peut pas réceptionner est un saut que l'on ne peut pas répéter.",
                    "Selalu empat langkah, dua terakhir cepat dan rendah, mendarat dua kaki.",
                    "Sentiasa empat langkah, dua terakhir pantas dan rendah, mendarat dua kaki.",
                    "สี่ก้าวทุกครั้ง สองก้าวสุดท้ายเร็วและต่ำ ลงสองเท้า กระโดดที่ลงไม่ดีคือกระโดดที่ทำซ้ำไม่ได้",
                    "Luôn bốn bước, hai bước cuối nhanh và thấp, tiếp đất bằng hai chân — cú bật không tiếp đất được là cú bật không lặp lại được."),
            home=[P(0.30, 0.72, "A",
                    moves=[(0.30, 0.56, 0), (0.30, 0.72, 1), (0.30, 0.56, 2), (0.30, 0.72, 3)],
                    why={0: "jump", 1: "reset", 2: "jump", 3: "reset"})],
            markers=[M(0.30, 0.70, "zone"), M(0.30, 0.55, "zone")],
            setup=_s("a hitter at the outside, behind the attack line, with nobody in front of him; a coach calls the tempo",
                     "主攻手站在 4 号位进攻线后，前方无人，由教练喊节奏",
                     "主攻手站在 4 號位進攻線後，前方無人，由教練喊節奏"),
            gear=_s("the two shaded zones are the start behind the attack line and the take-off spot at the net: every approach starts behind the line and takes off inside the other zone",
                    "两个阴影区分别是进攻线后的起点和网前的起跳区：每次助跑都从线后开始，在另一个区域内起跳",
                    "兩個陰影區分別是進攻線後的起點和網前的起跳區：每次助跑都從線後開始，在另一個區域內起跳"),
            flow=_s("Ten approach jumps in a row, swinging the arm each time, then 90 seconds' rest; three sets, and the front row and back row swap between sets.",
                    "连续做 10 次助跑起跳，每次都完整挥臂，然后休息 90 秒；做 3 组，组间前后排互换。",
                    "連續做 10 次助跑起跳，每次都完整揮臂，然後休息 90 秒；做 3 組，組間前後排互換。"),
        ),
        Drill(
            id="vbfit_block_shuffle", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.55, "A",
                    moves=[(0.22, 0.55, 0), (0.50, 0.55, 1), (0.78, 0.55, 2), (0.50, 0.55, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.22, 0.58), M(0.50, 0.58), M(0.78, 0.58)],
            setup=_s("a middle blocker at the net in the middle of the court, a cone at each pin and one in the middle",
                     "副攻站在网前中间位置，两个边（4 号位、2 号位）各一个锥标，中间一个锥标",
                     "副攻站在網前中間位置，兩個邊（4 號位、2 號位）各一個錐標，中間一個錐標"),
            gear=_s("three cones 3 m apart along the net are the blocking spots: middle, left pin, middle, right pin — a block jump at each, and the shuffle between them never crosses the feet",
                    "三个锥标沿网摆开、相距 3 米，是拦网的三个位置：中间、左边、中间、右边——每到一处起跳拦一次，移动全程并步不交叉",
                    "三個錐標沿網擺開、相距 3 米，是攔網的三個位置：中間、左邊、中間、右邊——每到一處起跳攔一次，移動全程併步不交叉"),
            flow=_s("Six block jumps is one set — middle, pin, middle, other pin, middle, pin — then 60 seconds' rest; four sets, and the last set is timed.",
                    "中—边—中—另一边—中—边，6 次拦网起跳为一组，然后休息 60 秒；做 4 组，最后一组计时。",
                    "中—邊—中—另一邊—中—邊，6 次攔網起跳為一組，然後休息 60 秒；做 4 組，最後一組計時。"),
        ),
        Drill(
            id="vbfit_six_point", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("Six-point court run", "六点场地跑", "六點場地跑", "6ポイント・コートラン",
                    "6포인트 코트 러닝", "Recorrido de seis puntos", "Parcours en six points",
                    "Lari enam titik", "Larian enam titik", "วิ่งหกจุดในคอร์ต", "Chạy sáu điểm trên sân"),
            note=_t("Touch the floor at every point with the hand: the drill is about getting low and standing up again, which is what digging is.",
                    "每个点都要用手触地：这个练习练的是蹲下去再起来——救球就是这件事。",
                    "每個點都要用手觸地：這個練習練的是蹲下去再起來——救球就是這件事。",
                    "各ポイントで必ず手で床にタッチする：低く沈んでまた立つ、それがレシーブそのものだ。",
                    "각 지점에서 손으로 바닥을 짚는다: 낮아졌다 다시 서는 것, 그것이 디그다.",
                    "Toca el suelo con la mano en cada punto: el ejercicio va de bajar y volver a subir, que es exactamente lo que es una defensa.",
                    "Touche le sol de la main à chaque point : l'exercice consiste à descendre et se relever, c'est exactement ce qu'est une défense.",
                    "Sentuh lantai dengan tangan di tiap titik: latihan ini soal turun rendah lalu bangkit lagi.",
                    "Sentuh lantai dengan tangan di setiap titik: latihan ini tentang turun rendah lalu bangkit semula.",
                    "แตะพื้นด้วยมือทุกจุด แบบฝึกนี้คือการย่อลงแล้วลุกขึ้น ซึ่งคือการรับลูกนั่นเอง",
                    "Chạm sàn bằng tay ở mỗi điểm: bài này là hạ thấp rồi đứng dậy — đó chính là động tác bắt bước một."),
            home=[P(0.50, 0.75, "A",
                    moves=[(0.18, 0.60, 0), (0.50, 0.75, 1), (0.82, 0.60, 2), (0.50, 0.75, 3),
                           (0.18, 0.92, 4), (0.50, 0.75, 5), (0.82, 0.92, 6), (0.50, 0.75, 7)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                         4: "sprint", 5: "turn_back", 6: "sprint", 7: "turn_back"})],
            markers=[M(0.15, 0.58), M(0.85, 0.58), M(0.15, 0.94), M(0.85, 0.94), M(0.50, 0.77)],
            setup=_s("a cone in the middle of the back court and four in the corners of the half; the player starts on the middle one",
                     "后场中间一个锥标，本方半场四个角各一个锥标，球员站在中间锥标上",
                     "後場中間一個錐標，本方半場四個角各一個錐標，球員站在中間錐標上"),
            gear=_s("the middle cone is base and the four corner cones are the points: go to each in turn and back to base, touching the floor at every one",
                    "中间锥标是原点，四个角的锥标是四个点：依次跑到每个点再回到原点，每个点都用手触地",
                    "中間錐標是原點，四個角的錐標是四個點：依次跑到每個點再回到原點，每個點都用手觸地"),
            flow=_s("Four points and back is one round, about 20 seconds; rest 40 seconds and go again. Six rounds, then swap with the next group.",
                    "四个点各去一次回来算一轮，约 20 秒；休息 40 秒再来。做 6 轮后换下一组。",
                    "四個點各去一次回來算一輪，約 20 秒；休息 40 秒再來。做 6 輪後換下一組。"),
        ),
    ]


# ══ badminton ════════════════════════════════════════════════════════════
def _badminton():
    return [
        Drill(
            id="bdfit_six_corner", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, free=True, name=SHADOW_NAME, note=SHADOW_NOTE,
            home=[P(0.50, 0.66, "A",
                    moves=[(0.28, 0.56, 0), (0.50, 0.66, 1), (0.72, 0.56, 2), (0.50, 0.66, 3),
                           (0.24, 0.88, 4), (0.50, 0.66, 5), (0.76, 0.88, 6), (0.50, 0.66, 7)],
                    why={0: "sprint", 1: "reset", 2: "sprint", 3: "reset",
                         4: "sprint", 5: "reset", 6: "sprint", 7: "reset"})],
            markers=[M(0.50, 0.68), M(0.26, 0.54), M(0.74, 0.54), M(0.22, 0.90), M(0.78, 0.90),
                     M(0.14, 0.68), M(0.86, 0.68)],
            setup=_s("a cone on base in the middle of the court and six around it — two at the net, two at the sides, two in the rear corners; the player starts on base",
                     "中心位放一个锥标，周围六个锥标：网前两个、两侧各一个、后场两角各一个，球员站在中心位",
                     "中心位放一個錐標，周圍六個錐標：網前兩個、兩側各一個、後場兩角各一個，球員站在中心位"),
            gear=_s("the middle cone is base and the six around it, about 3 m out, are the six corners a singles player covers — go to one, play the stroke, recover to base, and the coach points to the next",
                    "中间锥标是中心位，周围六个锥标是单打要覆盖的六个点，距离中心位约 3 米——到一个点做完击球动作、回到中心位，教练再指下一个",
                    "中間錐標是中心位，周圍六個錐標是單打要覆蓋的六個點，距離中心位約 3 米——到一個點做完擊球動作、回到中心位，教練再指下一個"),
            flow=_s("Thirty seconds of corners on the coach's hand, thirty seconds' rest; eight repetitions, then two minutes off and eight more. The recovery step back to base is part of every repetition.",
                    "教练用手指点位，做 30 秒、歇 30 秒；做 8 次后休息 2 分钟，再做 8 次。每一次都必须回到中心位才算一次。",
                    "教練用手指點位，做 30 秒、歇 30 秒；做 8 次後休息 2 分鐘，再做 8 次。每一次都必須回到中心位才算一次。"),
        ),
        Drill(
            id="bdfit_court_shuttle", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=SHUTTLE_NAME, note=SHUTTLE_NOTE,
            home=[P(0.50, 0.92, "A",
                    moves=[(0.50, 0.56, 0), (0.50, 0.92, 1), (0.50, 0.56, 2), (0.50, 0.92, 3)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back"})],
            setup=_s("the player on his own rear service line; the net and the rear line are the two ends",
                     "球员站在本方后发球线上，网前和后场线是两个端点",
                     "球員站在本方後發球線上，網前和後場線是兩個端點"),
            gear=_s("no equipment: the net and the rear court line are the turns — the racket touches the net cord at one end and the foot touches the line at the other",
                    "不需要器材：网和后场线就是两个折返点——前场用球拍触网带，后场用脚踩线",
                    "不需要器材：網和後場線就是兩個折返點——前場用球拍觸網帶，後場用腳踩線"),
            flow=_s("Six lengths is one set, about 25 seconds; rest 35 seconds and go again. Eight sets, and the last two should be within a second of the first two.",
                    "六趟为一组，约 25 秒；休息 35 秒再来。做 8 组，最后两组和前两组的时间差不能超过 1 秒。",
                    "六趟為一組，約 25 秒；休息 35 秒再來。做 8 組，最後兩組和前兩組的時間差不能超過 1 秒。"),
        ),
        Drill(
            id="bdfit_jump_smash_series", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.88, "A",
                    moves=[(0.50, 0.80, 0), (0.50, 0.88, 1), (0.50, 0.80, 2), (0.50, 0.88, 3)],
                    why={0: "jump", 1: "reset", 2: "jump", 3: "reset"})],
            markers=[M(0.42, 0.90), M(0.58, 0.90), M(0.50, 0.78, "zone")],
            setup=_s("the player behind his rear court line with room above him; nobody in front",
                     "球员站在后场线后方，头顶留出空间，前方无人",
                     "球員站在後場線後方，頭頂留出空間，前方無人"),
            gear=_s("the two cones are the rear line the jump starts behind; the shaded zone is where the landing has to be — forward of the take-off, never back onto the heels",
                    "两个锥标标出起跳前所在的后场线，阴影区是落地位置——要落在起跳点前方，绝不能后仰落在脚跟上",
                    "兩個錐標標出起跳前所在的後場線，陰影區是落地位置——要落在起跳點前方，絕不能後仰落在腳跟上"),
            flow=_s("Eight jump smashes in a row with the full swing, then 90 seconds' rest; four sets. Stop the set the moment a landing goes backwards.",
                    "连续做 8 次完整挥拍的跳杀，然后休息 90 秒；做 4 组。只要有一次落地向后，这一组立刻停。",
                    "連續做 8 次完整揮拍的跳殺，然後休息 90 秒；做 4 組。只要有一次落地向後，這一組立刻停。"),
        ),
    ]


# ══ tennis ═══════════════════════════════════════════════════════════════
def _tennis():
    return [
        Drill(
            id="tnfit_spider", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, free=True,
            name=_t("Spider run", "蜘蛛跑", "蜘蛛跑", "スパイダーラン", "스파이더 런",
                    "Carrera de la araña", "Course de l'araignée", "Lari laba-laba",
                    "Larian labah-labah", "สไปเดอร์รัน", "Chạy hình nhện"),
            note=_t("Five balls, five trips, one clock: the test is not how fast you run out, it is how little time you spend turning round.",
                    "五个球、五趟、一次计时：比的不是冲出去多快，而是转身花了多少时间。",
                    "五個球、五趟、一次計時：比的不是衝出去多快，而是轉身花了多少時間。",
                    "5球、5往復、1つの時計：速く出ることではなく、切り返しにどれだけ時間を使わないかが試される。",
                    "공 다섯 개, 다섯 번 왕복, 한 번의 시계: 얼마나 빨리 나가느냐가 아니라 돌아서는 데 시간을 얼마나 덜 쓰느냐다.",
                    "Cinco bolas, cinco viajes, un cronómetro: no se mide lo rápido que sales, sino lo poco que tardas en girar.",
                    "Cinq balles, cinq trajets, un chrono : on ne mesure pas la vitesse d'aller, mais le temps perdu à faire demi-tour.",
                    "Lima bola, lima perjalanan, satu stopwatch: yang diukur bukan seberapa cepat kamu keluar, tapi seberapa sedikit waktu untuk berbalik.",
                    "Lima bola, lima perjalanan, satu jam randik: yang diukur bukan kelajuan keluar, tetapi masa yang hilang ketika berpusing.",
                    "ห้าลูก ห้าเที่ยว จับเวลาครั้งเดียว วัดกันที่เสียเวลาหมุนตัวน้อยแค่ไหน ไม่ใช่วิ่งออกเร็วแค่ไหน",
                    "Năm bóng, năm lượt, một đồng hồ: đo không phải bạn chạy ra nhanh thế nào mà mất bao ít thời gian để quay lại."),
            home=[P(0.50, 0.95, "A",
                    moves=[(0.16, 0.70, 0), (0.50, 0.95, 1), (0.16, 0.95, 2), (0.50, 0.95, 3),
                           (0.50, 0.70, 4), (0.50, 0.95, 5), (0.84, 0.95, 6), (0.50, 0.95, 7),
                           (0.84, 0.70, 8), (0.50, 0.95, 9)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                         4: "sprint", 5: "turn_back", 6: "sprint", 7: "turn_back",
                         8: "sprint", 9: "turn_back"})],
            markers=[M(0.16, 0.68), M(0.16, 0.97), M(0.50, 0.68), M(0.84, 0.97), M(0.84, 0.68)],
            setup=_s("five cones — the two singles sideline corners at the baseline, the two service-line corners and the centre service mark; the player starts on the centre of the baseline",
                     "五个锥标：底线两个单打边角、发球线两个角、发球中点；球员站在底线中点",
                     "五個錐標：底線兩個單打邊角、發球線兩個角、發球中點；球員站在底線中點"),
            gear=_s("each cone stands in for a ball: fetch them one at a time in a fixed order and carry each back to the baseline centre before setting off for the next",
                    "每个锥标代表一个球：按固定顺序一次取一个，每取一个都要带回底线中点，再去下一个",
                    "每個錐標代表一個球：按固定順序一次取一個，每取一個都要帶回底線中點，再去下一個"),
            flow=_s("One full spider is the test, 16-18 seconds for a club player; three runs with two minutes between them, and note the best.",
                    "跑完整套算一次测试，业余球员 16–18 秒；做 3 次，每次之间休息 2 分钟，记录最好成绩。",
                    "跑完整套算一次測試，業餘球員 16–18 秒；做 3 次，每次之間休息 2 分鐘，記錄最好成績。"),
        ),
        Drill(
            id="tnfit_baseline_side_to_side", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.50, 0.92, "A",
                    moves=[(0.18, 0.92, 0), (0.50, 0.92, 1), (0.82, 0.92, 2), (0.50, 0.92, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.16, 0.95), M(0.50, 0.95), M(0.84, 0.95)],
            setup=_s("three cones on the baseline — both singles corners and the centre mark; the player starts on the centre",
                     "底线上三个锥标：单打两个边角和中点；球员从中点出发",
                     "底線上三個錐標：單打兩個邊角和中點；球員從中點出發"),
            gear=_s("the cones are the corners the recovery step has to reach: side-shuffle out, play the stroke, cross-step back through the middle cone",
                    "锥标是回位必须到达的两个边角：并步横移出去、做出击球动作，再交叉步经中间锥标回来",
                    "錐標是回位必須到達的兩個邊角：併步橫移出去、做出擊球動作，再交叉步經中間錐標回來"),
            flow=_s("Twenty seconds of side to side, forty seconds' rest; ten repetitions. Play the shadow forehand and backhand at the cones — the swing is what keeps it a tennis drill.",
                    "左右移动 20 秒、休息 40 秒，做 10 次。到锥标处要做出正手和反手的挥拍动作——有挥拍才是网球练习。",
                    "左右移動 20 秒、休息 40 秒，做 10 次。到錐標處要做出正手和反手的揮拍動作——有揮拍才是網球練習。"),
        ),
        Drill(
            id="tnfit_up_and_back", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.50, 0.93, "A",
                    moves=[(0.50, 0.56, 0), (0.50, 0.93, 1), (0.50, 0.56, 2), (0.50, 0.93, 3)],
                    why={0: "sprint", 1: "backpedal", 2: "sprint", 3: "backpedal"})],
            markers=[M(0.50, 0.95), M(0.50, 0.54)],
            setup=_s("two cones, one on the baseline centre mark and one at the net post line; the player starts on the baseline",
                     "两个锥标：一个在底线中点，一个在网前；球员从底线出发",
                     "兩個錐標：一個在底線中點，一個在網前；球員從底線出發"),
            gear=_s("the far cone is the net: sprint in and touch it, then backpedal to the baseline cone facing the net the whole way — never turn your back on the court",
                    "远端锥标代表网前：冲上去触到它，再全程面向球网后退跑回底线锥标——不要背对球场跑",
                    "遠端錐標代表網前：衝上去觸到它，再全程面向球網後退跑回底線錐標——不要背對球場跑"),
            flow=_s("Six in and outs is one set, then 90 seconds' rest; five sets. Add a split-step at the net cone once the legs are tired — that is when it stops happening.",
                    "上网—退底线做 6 次为一组，休息 90 秒；做 5 组。腿累了以后要求在网前锥标处加一个分腿垫步——恰恰是这时候它最容易消失。",
                    "上網—退底線做 6 次為一組，休息 90 秒；做 5 組。腿累了以後要求在網前錐標處加一個分腿墊步——恰恰是這時候它最容易消失。"),
        ),
    ]


# ══ pickleball ═══════════════════════════════════════════════════════════
def _pickleball():
    return [
        Drill(
            id="pbfit_kitchen_shuffle", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, free=True, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.50, 0.68, "A",
                    moves=[(0.20, 0.68, 0), (0.50, 0.68, 1), (0.80, 0.68, 2), (0.50, 0.68, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.18, 0.70), M(0.50, 0.70), M(0.82, 0.70)],
            setup=_s("three cones just behind the kitchen line — both sidelines and the middle; the player starts in the middle with the paddle up",
                     "厨房线后方三个锥标：两条边线和中间；球员站在中间，球拍举在身前",
                     "廚房線後方三個錐標：兩條邊線和中間；球員站在中間，球拍舉在身前"),
            gear=_s("the cones mark the kitchen line the feet must stay behind: shuffle to the sideline cone and back without the toes crossing the line and without the paddle dropping",
                    "锥标标出脚必须留在其后的厨房线：并步移到边线锥标再回来，脚尖不过线、球拍不落下",
                    "錐標標出腳必須留在其後的廚房線：併步移到邊線錐標再回來，腳尖不過線、球拍不落下"),
            flow=_s("Thirty seconds of shuffling, thirty seconds' rest; ten repetitions. If the paddle drops below the chest the repetition does not count.",
                    "滑步 30 秒、休息 30 秒，做 10 次。球拍掉到胸口以下的那一次不算。",
                    "滑步 30 秒、休息 30 秒，做 10 次。球拍掉到胸口以下的那一次不算。"),
        ),
        Drill(
            id="pbfit_transition", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("Transition zone up and back", "过渡区上下移动", "過渡區上下移動",
                    "トランジションゾーンの往復", "트랜지션 존 전후 이동",
                    "Zona de transición, ida y vuelta", "Zone de transition, aller-retour",
                    "Zona transisi maju mundur", "Zon peralihan ke depan dan belakang",
                    "เคลื่อนที่เข้าออกโซนเปลี่ยนผ่าน", "Lên xuống vùng chuyển tiếp"),
            note=_t("Never move while the imaginary ball is coming: two steps, split-step, two steps. The transition zone punishes running through it, not being in it.",
                    "球（假想的）来的时候不要移动：两步、分腿垫步、再两步。过渡区惩罚的是从中间一路跑过去，而不是待在里面。",
                    "球（假想的）來的時候不要移動：兩步、分腿墊步、再兩步。過渡區懲罰的是從中間一路跑過去，而不是待在裡面。",
                    "（想定の）球が来ている間は動かない：2歩、スプリットステップ、2歩。トランジションゾーンが罰するのは走り抜けることで、そこにいること自体ではない。",
                    "(가상의) 공이 오는 동안에는 움직이지 않는다: 두 걸음, 스플릿 스텝, 두 걸음. 트랜지션 존은 그냥 뛰어 통과하는 것을 벌하지, 거기 있는 것을 벌하지 않는다.",
                    "No te muevas mientras la bola imaginaria viene: dos pasos, split-step, dos pasos. La zona de transición castiga atravesarla corriendo, no estar en ella.",
                    "Ne bouge pas pendant que la balle imaginaire arrive : deux pas, split-step, deux pas. La zone de transition punit celui qui la traverse en courant, pas celui qui s'y trouve.",
                    "Jangan bergerak saat bola khayalan sedang datang: dua langkah, split-step, dua langkah.",
                    "Jangan bergerak ketika bola bayangan sedang datang: dua langkah, split-step, dua langkah.",
                    "อย่าเคลื่อนที่ขณะลูก (สมมติ) กำลังมา สองก้าว สปลิตสเต็ป สองก้าว",
                    "Đừng di chuyển khi bóng (tưởng tượng) đang tới: hai bước, split-step, hai bước."),
            home=[P(0.50, 0.95, "A",
                    moves=[(0.50, 0.82, 0), (0.50, 0.70, 1), (0.50, 0.82, 2), (0.50, 0.95, 3)],
                    why={0: "decel", 1: "decel", 2: "backpedal", 3: "backpedal"})],
            markers=[M(0.42, 0.97), M(0.58, 0.97), M(0.42, 0.70), M(0.58, 0.70)],
            setup=_s("two cones on the baseline and two on the kitchen line; the player starts on the baseline",
                     "底线两个锥标、厨房线两个锥标；球员从底线出发",
                     "底線兩個錐標、廚房線兩個錐標；球員從底線出發"),
            gear=_s("the baseline pair is the start and the kitchen pair is the destination: two steps in, split-step, two more, split-step — and backpedal out the same way",
                    "底线一对是起点，厨房线一对是终点：进两步、分腿垫步、再两步、再垫步——然后以同样的方式后退出来",
                    "底線一對是起點，廚房線一對是終點：進兩步、分腿墊步、再兩步、再墊步——然後以同樣的方式後退出來"),
            flow=_s("In and out four times is one set, then 60 seconds' rest; five sets. Every split-step is a stop, so a set with no stops in it has not been done.",
                    "进出四次为一组，休息 60 秒；做 5 组。每个分腿垫步都是一次停顿，一组里没有停顿就等于没做。",
                    "進出四次為一組，休息 60 秒；做 5 組。每個分腿墊步都是一次停頓，一組裡沒有停頓就等於沒做。"),
        ),
        Drill(
            id="pbfit_four_corner", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.50, 0.82, "A",
                    moves=[(0.20, 0.70, 0), (0.50, 0.82, 1), (0.80, 0.70, 2), (0.50, 0.82, 3),
                           (0.20, 0.95, 4), (0.50, 0.82, 5), (0.80, 0.95, 6), (0.50, 0.82, 7)],
                    why={0: "sprint", 1: "reset", 2: "sprint", 3: "reset",
                         4: "sprint", 5: "reset", 6: "sprint", 7: "reset"})],
            markers=[M(0.18, 0.70), M(0.82, 0.70), M(0.18, 0.97), M(0.82, 0.97), M(0.50, 0.84)],
            setup=_s("a cone in the middle of the half and four in its corners — two at the kitchen line, two on the baseline; the player starts on the middle one",
                     "半场中间一个锥标，四角各一个：厨房线两个、底线两个；球员站在中间锥标上",
                     "半場中間一個錐標，四角各一個：廚房線兩個、底線兩個；球員站在中間錐標上"),
            gear=_s("the middle cone is base and the four corners are the points: reach each with the paddle, recover to base, and the coach calls the order",
                    "中间锥标是原点，四个角是四个点：用球拍够到每个点后回到原点，顺序由教练喊",
                    "中間錐標是原點，四個角是四個點：用球拍夠到每個點後回到原點，順序由教練喊"),
            flow=_s("Four corners and back is one round, about 18 seconds; rest 40 seconds and go again. Six rounds, then the pair swaps.",
                    "四个角各去一次回来算一轮，约 18 秒；休息 40 秒再来。做 6 轮后两人互换。",
                    "四個角各去一次回來算一輪，約 18 秒；休息 40 秒再來。做 6 輪後兩人互換。"),
        ),
    ]


# ══ table tennis ═════════════════════════════════════════════════════════
def _table_tennis():
    return [
        Drill(
            id="ttfit_side_step", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, free=True, name=SHADOW_NAME, note=SHADOW_NOTE,
            home=[P(0.50, 0.86, "A",
                    moves=[(0.24, 0.86, 0), (0.50, 0.86, 1), (0.76, 0.86, 2), (0.50, 0.86, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.20, 0.90), M(0.50, 0.90), M(0.80, 0.90)],
            setup=_s("three cones on the floor behind the table — the two corners and the middle; the player starts in the middle in his playing stance",
                     "球台后方地面放三个锥标：两个角和中间；球员在中间以击球站位站好",
                     "球台後方地面放三個錐標：兩個角和中間；球員在中間以擊球站位站好"),
            gear=_s("the cones are the two corners of the table and the middle: side-step to a corner, play the stroke, side-step back — the feet stay behind the cones, never under the table",
                    "锥标代表球台的两个角和中间：并步移到一个角做出击球动作再移回来——脚始终在锥标后面，不要钻到台下",
                    "錐標代表球檯的兩個角和中間：併步移到一個角做出擊球動作再移回來——腳始終在錐標後面，不要鑽到檯下"),
            flow=_s("Thirty seconds of side-stepping with the full stroke, thirty seconds' rest; twelve repetitions. Count the strokes and try to beat the count next time.",
                    "带完整挥拍的并步移动 30 秒、休息 30 秒，做 12 次。数一数挥了多少拍，下次争取更多。",
                    "帶完整揮拍的併步移動 30 秒、休息 30 秒，做 12 次。數一數揮了多少拍，下次爭取更多。"),
        ),
        Drill(
            id="ttfit_in_and_out", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("In and out of the table", "进台退台步法", "進檯退檯步法", "前後のフットワーク",
                    "전후 스텝", "Entrar y salir de la mesa", "Avancer-reculer à la table",
                    "Maju mundur ke meja", "Ke depan dan belakang meja", "ฟุตเวิร์กเข้าออกโต๊ะ",
                    "Bước vào ra khỏi bàn"),
            note=_t("In with a small step, out with two — the mistake is going in with a big step, because then there is no way back for the next ball.",
                    "进台用小步，退台用两步——错误是进台迈一大步，那样下一板就退不出来了。",
                    "進檯用小步，退檯用兩步——錯誤是進檯邁一大步，那樣下一板就退不出來了。",
                    "入るときは小さく一歩、出るときは二歩——大きく踏み込むのが失敗で、次の球に下がれなくなる。",
                    "들어갈 때는 작은 한 걸음, 나올 때는 두 걸음 — 크게 들어가는 것이 실수다. 그러면 다음 공에 물러날 수 없다.",
                    "Entrar con un paso corto, salir con dos: el error es entrar con una zancada, porque entonces no hay vuelta para la siguiente bola.",
                    "Entrer d'un petit pas, sortir en deux : l'erreur est d'entrer d'une grande enjambée, car il n'y a plus de retour pour la balle suivante.",
                    "Masuk dengan langkah kecil, keluar dengan dua — kesalahannya masuk dengan langkah besar.",
                    "Masuk dengan langkah kecil, keluar dengan dua — kesilapannya masuk dengan langkah besar.",
                    "เข้าโต๊ะก้าวเล็ก ออกสองก้าว ความผิดพลาดคือเข้าด้วยก้าวใหญ่ แล้วถอยไม่ทันลูกถัดไป",
                    "Vào bằng một bước nhỏ, ra bằng hai bước — sai lầm là bước vào quá dài, khi đó không kịp lùi cho quả sau."),
            home=[P(0.50, 0.88, "A",
                    moves=[(0.50, 0.78, 0), (0.50, 0.88, 1), (0.50, 0.96, 2), (0.50, 0.88, 3)],
                    why={0: "decel", 1: "backpedal", 2: "backpedal", 3: "reset"})],
            markers=[M(0.44, 0.76), M(0.56, 0.76), M(0.44, 0.98), M(0.56, 0.98)],
            setup=_s("two cones close to the end of the table and two a step and a half behind them; the player starts between the pairs",
                     "球台端线附近两个锥标，其后一步半再放两个锥标；球员站在两对锥标之间",
                     "球檯端線附近兩個錐標，其後一步半再放兩個錐標；球員站在兩對錐標之間"),
            gear=_s("the near pair is the short-ball position at the table, the far pair the deep position: step in between the near cones for the short ball, out behind the far cones for the deep one",
                    "近端一对是台内处理短球的位置，远端一对是退台击球的位置：处理短球进到近端锥标之间，打长球退到远端锥标之后",
                    "近端一對是檯內處理短球的位置，遠端一對是退檯擊球的位置：處理短球進到近端錐標之間，打長球退到遠端錐標之後"),
            flow=_s("Twenty seconds in and out with the stroke at each end, forty seconds' rest; ten repetitions, and the last three with the coach calling short or long at random.",
                    "进台退台做 20 秒，两端都要挥拍，休息 40 秒，做 10 次；最后 3 次由教练随机喊短球或长球。",
                    "進檯退檯做 20 秒，兩端都要揮拍，休息 40 秒，做 10 次；最後 3 次由教練隨機喊短球或長球。"),
        ),
        Drill(
            id="ttfit_figure_eight", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.50, 0.86, "A",
                    moves=[(0.24, 0.78, 0), (0.50, 0.94, 1), (0.76, 0.78, 2), (0.50, 0.94, 3)],
                    why={0: "sprint", 1: "shuffle", 2: "sprint", 3: "shuffle"})],
            markers=[M(0.20, 0.76), M(0.80, 0.76), M(0.50, 0.96)],
            setup=_s("three cones behind the table in a triangle — two wide and forward, one back in the middle; the player starts between them",
                     "球台后方三个锥标呈三角形：两个在两侧偏前，一个在后方中间；球员站在三者之间",
                     "球檯後方三個錐標呈三角形：兩個在兩側偏前，一個在後方中間；球員站在三者之間"),
            gear=_s("the two forward cones are the forehand and backhand corners at the table and the back cone is the deep recovery position; the path round them is a figure of eight",
                    "两个靠前的锥标是台边的正手位和反手位，后方锥标是退台后的回位点；绕行路线是一个八字",
                    "兩個靠前的錐標是檯邊的正手位和反手位，後方錐標是退檯後的回位點；繞行路線是一個八字"),
            flow=_s("Twenty-five seconds of figure-eights, thirty-five seconds' rest; ten repetitions, and the feet do not stop moving inside a repetition.",
                    "八字移动 25 秒、休息 35 秒，做 10 次；一次之内脚不许停下来。",
                    "八字移動 25 秒、休息 35 秒，做 10 次；一次之內腳不許停下來。"),
        ),
    ]


# ══ handball ═════════════════════════════════════════════════════════════
def _handball():
    return [
        Drill(
            id="hbfit_court_shuttle", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, free=True, name=SHUTTLE_NAME, note=SHUTTLE_NOTE,
            home=[P(0.50, 0.90, "A",
                    moves=[(0.50, 0.72, 0), (0.50, 0.90, 1), (0.50, 0.50, 2), (0.50, 0.90, 3),
                           (0.50, 0.28, 4), (0.50, 0.90, 5)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                         4: "sprint", 5: "turn_back"})],
            setup=_s("the player on his own nine-metre line; the court's own lines are the turns",
                     "球员站在本方九米线上，场地自带的线就是折返点",
                     "球員站在本方九米線上，場地自帶的線就是折返點"),
            gear=_s("no equipment: the free-throw line, the halfway line and the far free-throw line are the three turns, each touched with the hand",
                    "不需要器材：本方九米线、中线、对方九米线是三个折返点，每个都用手触线",
                    "不需要器材：本方九米線、中線、對方九米線是三個折返點，每個都用手觸線"),
            flow=_s("Three out-and-backs is one shuttle; rest 45 seconds and go again. Eight shuttles, and a wing who cannot hold the time is a wing who will not get back on the break.",
                    "三个折返为一趟；休息 45 秒再来。做 8 趟——守不住时间的边锋，快攻也退不回来。",
                    "三個折返為一趟；休息 45 秒再來。做 8 趟——守不住時間的邊鋒，快攻也退不回來。"),
        ),
        Drill(
            id="hbfit_jump_series", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.74, "A",
                    moves=[(0.50, 0.66, 0), (0.50, 0.74, 1), (0.50, 0.66, 2), (0.50, 0.74, 3)],
                    why={0: "jump", 1: "reset", 2: "jump", 3: "reset"})],
            markers=[M(0.50, 0.76, "zone"), M(0.50, 0.64, "zone")],
            setup=_s("a back court player behind the nine-metre line with the goal area in front of him and nobody in it",
                     "后卫站在九米线后，身前是空的六米区",
                     "後衛站在九米線後，身前是空的六米區"),
            gear=_s("the near zone is the three-step run-up behind the nine-metre line and the far zone is where the take-off foot lands: every jump starts and lands inside them, never over the goal-area line",
                    "近端阴影区是九米线后的三步助跑区，远端阴影区是起跳脚落点：每次起跳都在这两个区内完成，不得越过六米线",
                    "近端陰影區是九米線後的三步助跑區，遠端陰影區是起跳腳落點：每次起跳都在這兩個區內完成，不得越過六米線"),
            flow=_s("Eight jumps with the full throwing action, then 90 seconds' rest; four sets. The arm is thrown every time — a jump without the arm is half the load.",
                    "带完整投篮（射门）动作的起跳做 8 次，休息 90 秒；做 4 组。每次都要把手臂甩出去——不甩臂只有一半的负荷。",
                    "帶完整投籃（射門）動作的起跳做 8 次，休息 90 秒；做 4 組。每次都要把手臂甩出去——不甩臂只有一半的負荷。"),
        ),
        Drill(
            id="hbfit_break_repeats", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.20, 0.88, "A",
                    moves=[(0.20, 0.20, 0), (0.50, 0.88, 1)],
                    why={0: "sprint", 1: "jog"})],
            markers=[M(0.16, 0.90), M(0.16, 0.18)],
            setup=_s("a cone on each wing position at the two ends of the court; the wing starts on the defensive one",
                     "两端边锋位各放一个锥标；边锋从防守端的锥标出发",
                     "兩端邊鋒位各放一個錐標；邊鋒從防守端的錐標出發"),
            gear=_s("the two cones are the wing's two ends, a full court apart (40 m): the sprint is the first wave of the break, wide, and the jog back is down the middle so the next runner has the lane",
                    "两个锥标是边锋的两端，相距一整片场地（40 米）：冲刺是快攻第一波，沿边路；慢跑回来走中间，把边路让给下一个人",
                    "兩個錐標是邊鋒的兩端，相距一整片場地（40 米）：衝刺是快攻第一波，沿邊路；慢跑回來走中間，把邊路讓給下一個人"),
            flow=_s("Sprint the length, jog back inside 35 seconds and go again; ten breaks, then five minutes and the other wing.",
                    "全场冲刺一趟，35 秒内慢跑回来再出发；做 10 次，休息 5 分钟后换另一侧边锋位。",
                    "全場衝刺一趟，35 秒內慢跑回來再出發；做 10 次，休息 5 分鐘後換另一側邊鋒位。"),
        ),
    ]


# ══ rugby ════════════════════════════════════════════════════════════════
def _rugby():
    return [
        Drill(
            id="rgfit_bronco", category="conditioning", minutes=12, rel=True,
            purpose=PURPOSE_COURT, free=True,
            name=_t("Bronco", "Bronco 折返测试", "Bronco 折返測試", "ブロンコ", "브롱코",
                    "Bronco", "Bronco", "Bronco", "Bronco", "บรองโก้", "Bronco"),
            note=_t("Five sets of 20-40-60 without stopping: the first shuttle tells you nothing, the fourth tells you everything about the last twenty minutes of a match.",
                    "20-40-60 米连续做五轮，中间不停：第一轮说明不了什么，第四轮说明的就是比赛最后二十分钟。",
                    "20-40-60 米連續做五輪，中間不停：第一輪說明不了什麼，第四輪說明的就是比賽最後二十分鐘。",
                    "20-40-60を止まらずに5セット：1セット目は何も語らないが、4セット目は試合の最後の20分をそのまま語る。",
                    "20-40-60을 쉬지 않고 다섯 세트: 첫 세트는 아무것도 말해주지 않지만, 네 번째 세트는 경기 마지막 20분을 그대로 말해준다.",
                    "Cinco series de 20-40-60 sin parar: la primera no dice nada, la cuarta lo dice todo sobre los últimos veinte minutos de un partido.",
                    "Cinq séries de 20-40-60 sans s'arrêter : la première ne dit rien, la quatrième dit tout des vingt dernières minutes d'un match.",
                    "Lima set 20-40-60 tanpa berhenti: set pertama tak berarti, set keempat menjelaskan dua puluh menit terakhir pertandingan.",
                    "Lima set 20-40-60 tanpa berhenti: set pertama tidak bermakna, set keempat menjelaskan dua puluh minit terakhir perlawanan.",
                    "วิ่ง 20-40-60 ห้าเซ็ตไม่หยุด เซ็ตแรกไม่บอกอะไร เซ็ตสี่บอกทุกอย่างเรื่องยี่สิบนาทีสุดท้ายของเกม",
                    "Năm hiệp 20-40-60 không nghỉ: hiệp đầu không nói gì, hiệp bốn nói tất cả về hai mươi phút cuối trận."),
            home=[P(0.50, 0.84, "A",
                    moves=[(0.50, 0.70, 0), (0.50, 0.84, 1), (0.50, 0.56, 2), (0.50, 0.84, 3),
                           (0.50, 0.42, 4), (0.50, 0.84, 5)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                         4: "sprint", 5: "turn_back"})],
            markers=[M(0.42, 0.86), M(0.42, 0.70), M(0.42, 0.56), M(0.42, 0.42)],
            setup=_s("four cones on a line at 0, 20, 40 and 60 m; the player starts on the first",
                     "一条线上放四个锥标，分别在 0、20、40、60 米处，跑者从第一个出发",
                     "一條線上放四個錐標，分別在 0、20、40、60 米處，跑者從第一個出發"),
            gear=_s("the cones are the 20, 40 and 60 m turns: out to each and back to the start, and the turn is made by touching the line at the cone, not swinging round it",
                    "锥标是 20、40、60 米的折返点：每个都跑到再折回起点；折返要踩线，不许绕着锥标画弧",
                    "錐標是 20、40、60 米的折返點：每個都跑到再折回起點；折返要踩線，不許繞著錐標畫弧"),
            flow=_s("20-40-60 is one set and five sets is a bronco, run without rest — a forward pack around 5:30, backs under 5:00. Once a fortnight, never the day before a match.",
                    "20-40-60 为一轮，连做五轮为一次 Bronco，中间不休息——前锋组约 5 分 30 秒，后卫线 5 分以内。每两周一次，赛前一天绝不做。",
                    "20-40-60 為一輪，連做五輪為一次 Bronco，中間不休息——前鋒組約 5 分 30 秒，後衛線 5 分以內。每兩週一次，賽前一天絕不做。"),
        ),
        Drill(
            id="rgfit_up_downs", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("Up-downs", "起倒冲刺", "起倒衝刺", "アップダウン", "업다운",
                    "Tumbarse y levantarse", "Se coucher-se relever", "Jatuh bangun",
                    "Jatuh bangun", "ลงพื้น-ลุกวิ่ง", "Nằm xuống - bật dậy"),
            note=_t("Chest to the ground and up facing forward — getting up is the skill, and after a tackle the man who is up first is the man who makes the next one.",
                    "胸口贴地，起来时面朝前——爬起来才是技术；一次擒抱之后，先站起来的人才能做下一次。",
                    "胸口貼地，起來時面朝前——爬起來才是技術；一次擒抱之後，先站起來的人才能做下一次。",
                    "胸を地面につけ、前を向いて立つ——起き上がることこそ技術で、タックルの後は先に立った者が次のタックルをする。",
                    "가슴을 땅에 대고 앞을 보며 일어난다 — 일어나는 것이 기술이고, 태클 뒤에 먼저 일어난 사람이 다음 태클을 한다.",
                    "Pecho al suelo y arriba mirando al frente: levantarse es la habilidad, y tras un placaje el que se levanta primero hace el siguiente.",
                    "Poitrine au sol et debout face au jeu : se relever est la compétence, et après un plaquage celui qui se relève le premier fait le suivant.",
                    "Dada menyentuh tanah lalu bangkit menghadap ke depan — bangkit itulah keterampilannya.",
                    "Dada menyentuh tanah lalu bangun menghadap ke hadapan — bangun itulah kemahirannya.",
                    "อกแตะพื้นแล้วลุกขึ้นหันหน้าไปข้างหน้า การลุกคือทักษะ หลังแท็กเกิลใครลุกก่อนคนนั้นได้ทำครั้งต่อไป",
                    "Ngực chạm đất rồi bật dậy hướng về phía trước — đứng dậy mới là kỹ năng; sau một pha tắc bóng, ai dậy trước người đó làm pha tiếp theo."),
            home=[P(0.50, 0.80, "A",
                    moves=[(0.50, 0.74, 0), (0.50, 0.68, 1), (0.50, 0.56, 2), (0.50, 0.80, 3)],
                    why={0: "touch_down", 1: "touch_down", 2: "sprint", 3: "jog"})],
            markers=[M(0.42, 0.82), M(0.58, 0.82), M(0.42, 0.54), M(0.58, 0.54)],
            setup=_s("two cones as a start gate and two more 20 m ahead; the player starts standing at the gate",
                     "两个锥标作为起点门，前方 20 米再放两个；球员在起点门处站立准备",
                     "兩個錐標作為起點門，前方 20 米再放兩個；球員在起點門處站立準備"),
            gear=_s("the near pair is where the up-downs are done and the far pair is the sprint line: three up-downs on the spot, then sprint through the far gate",
                    "近端一对是做起倒动作的位置，远端一对是冲刺终点线：原地做三次起倒，然后冲过远端的门",
                    "近端一對是做起倒動作的位置，遠端一對是衝刺終點線：原地做三次起倒，然後衝過遠端的門"),
            flow=_s("Three up-downs and a 20 m sprint is one rep, jog back and the next player goes; eight reps each, two sets, three minutes between sets.",
                    "三次起倒加 20 米冲刺为一次，慢跑回来后下一人出发；每人 8 次一组，做 2 组，组间休息 3 分钟。",
                    "三次起倒加 20 米衝刺為一次，慢跑回來後下一人出發；每人 8 次一組，做 2 組，組間休息 3 分鐘。"),
        ),
        Drill(
            id="rgfit_repeat_sprints", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.30, 0.82, "A",
                    moves=[(0.30, 0.44, 0), (0.50, 0.82, 1)],
                    why={0: "sprint", 1: "jog"})],
            markers=[M(0.26, 0.84), M(0.26, 0.42)],
            setup=_s("two cones 40 m apart; the group lines up on the first and goes in pairs",
                     "两个锥标相距 40 米；全组在第一个锥标排队，两人一组出发",
                     "兩個錐標相距 40 米；全組在第一個錐標排隊，兩人一組出發"),
            gear=_s("the two cones are the 40 m the sprint covers; the jog back inside the cones is the recovery and is timed as strictly as the sprint",
                    "两个锥标之间是 40 米冲刺距离；沿内侧慢跑回来是恢复段，和冲刺一样严格计时",
                    "兩個錐標之間是 40 米衝刺距離；沿內側慢跑回來是恢復段，和衝刺一樣嚴格計時"),
            flow=_s("Forty metres flat out, 25 seconds to jog back and go again; eight sprints a set, three sets, four minutes between sets.",
                    "40 米全力冲刺，25 秒内慢跑回来再出发；8 次一组，做 3 组，组间休息 4 分钟。",
                    "40 米全力衝刺，25 秒內慢跑回來再出發；8 次一組，做 3 組，組間休息 4 分鐘。"),
        ),
    ]


# ══ field hockey ═════════════════════════════════════════════════════════
def _field_hockey():
    return [
        Drill(
            id="fhfit_shuttle", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, free=True, name=SHUTTLE_NAME, note=SHUTTLE_NOTE,
            home=[P(0.50, 0.88, "A",
                    moves=[(0.50, 0.74, 0), (0.50, 0.88, 1), (0.50, 0.60, 2), (0.50, 0.88, 3),
                           (0.50, 0.46, 4), (0.50, 0.88, 5)],
                    why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                         4: "sprint", 5: "turn_back"})],
            markers=[M(0.42, 0.90), M(0.42, 0.74), M(0.42, 0.60), M(0.42, 0.46)],
            setup=_s("four cones on a line at 0, 10, 20 and 30 m; the player starts on the first, stick in both hands",
                     "一条线上四个锥标，分别在 0、10、20、30 米处；球员双手持棍从第一个出发",
                     "一條線上四個錐標，分別在 0、10、20、30 米處；球員雙手持棍從第一個出發"),
            gear=_s("the cones are the 10, 20 and 30 m turns; the stick touches the line at every turn, which means the body is already low when it does",
                    "锥标是 10、20、30 米的折返点；每次折返用球棍触线——这样身体在折返时自然就是低位",
                    "錐標是 10、20、30 米的折返點；每次折返用球棍觸線——這樣身體在折返時自然就是低位"),
            flow=_s("Three out-and-backs is one shuttle, about 30 seconds; rest 45 seconds and go again. Eight shuttles, then five minutes.",
                    "三个折返为一趟，约 30 秒；休息 45 秒再来。做 8 趟后休息 5 分钟。",
                    "三個折返為一趟，約 30 秒；休息 45 秒再來。做 8 趟後休息 5 分鐘。"),
        ),
        Drill(
            id="fhfit_low_lateral", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.50, 0.78, "A",
                    moves=[(0.24, 0.78, 0), (0.50, 0.78, 1), (0.76, 0.78, 2), (0.50, 0.78, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.22, 0.81), M(0.50, 0.81), M(0.78, 0.81)],
            setup=_s("three cones 6 m apart across the 23 m line; the player starts on the middle one in the tackling position",
                     "23 米线上三个锥标，相距 6 米；球员以抢断姿势从中间锥标出发",
                     "23 米線上三個錐標，相距 6 米；球員以搶斷姿勢從中間錐標出發"),
            gear=_s("the cones are the width the defender has to cover: shuffle to each with the stick down on the turf, and the stick never comes up between them",
                    "锥标之间是防守者要覆盖的宽度：滑步到每个锥标，球棍始终贴地，移动中不许抬起来",
                    "錐標之間是防守者要覆蓋的寬度：滑步到每個錐標，球棍始終貼地，移動中不許抬起來"),
            flow=_s("Twenty-five seconds of shuffling with the stick down, thirty-five seconds' rest; ten repetitions. A stick that lifts ends the repetition.",
                    "球棍贴地滑步 25 秒、休息 35 秒，做 10 次。球棍一抬起来，这一次就结束。",
                    "球棍貼地滑步 25 秒、休息 35 秒，做 10 次。球棍一抬起來，這一次就結束。"),
        ),
        Drill(
            id="fhfit_repeat_sprints", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.24, 0.84, "A",
                    moves=[(0.24, 0.30, 0), (0.50, 0.84, 1)],
                    why={0: "sprint", 1: "jog"})],
            markers=[M(0.20, 0.86), M(0.20, 0.28)],
            setup=_s("two cones 40 m apart down one side of the pitch; the group goes in pairs",
                     "球场一侧两个锥标相距 40 米；全组两人一组出发",
                     "球場一側兩個錐標相距 40 米；全組兩人一組出發"),
            gear=_s("the two cones are the 40 m of the sprint, run on the side of the pitch a winger covers; the jog back is inside them",
                    "两个锥标之间是 40 米冲刺距离，沿边锋负责的边路跑；沿内侧慢跑回来",
                    "兩個錐標之間是 40 米衝刺距離，沿邊鋒負責的邊路跑；沿內側慢跑回來"),
            flow=_s("Forty metres flat out, 25 seconds to jog back; eight sprints a set, three sets, four minutes between sets. Carry the stick throughout — it changes how the arms run.",
                    "40 米全力冲刺，25 秒内慢跑回来；8 次一组，做 3 组，组间休息 4 分钟。全程持棍——它会改变手臂的摆动方式。",
                    "40 米全力衝刺，25 秒內慢跑回來；8 次一組，做 3 組，組間休息 4 分鐘。全程持棍——它會改變手臂的擺動方式。"),
        ),
    ]


# ══ water polo ═══════════════════════════════════════════════════════════
def _water_polo():
    return [
        Drill(
            id="wpfit_eggbeater", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_WATER, free=True,
            name=_t("Eggbeater intervals", "踩水间歇", "踩水間歇", "巻き足インターバル",
                    "에그비터 인터벌", "Intervalos de batido", "Intervalles d'eggbeater",
                    "Interval eggbeater", "Selang eggbeater", "อินเทอร์วัลปั่นขา", "Đạp nước ngắt quãng"),
            note=_t("Hands out of the water and held there: the legs do the work, and the moment a hand slaps the surface for help the interval is over.",
                    "双手举出水面并保持住：完全靠腿；只要有一只手拍水借力，这一组就结束。",
                    "雙手舉出水面並保持住：完全靠腿；只要有一隻手拍水借力，這一組就結束。",
                    "手は水面より上に出したまま保つ：仕事は脚がする。助けを求めて手が水を叩いた瞬間、そのインターバルは終わりだ。",
                    "손은 물 밖으로 들고 유지한다: 다리가 일한다. 손이 물을 치며 도움을 구하는 순간 인터벌은 끝난다.",
                    "Manos fuera del agua y mantenidas ahí: trabajan las piernas, y en cuanto una mano golpea la superficie para ayudarse, el intervalo se acabó.",
                    "Mains hors de l'eau et maintenues : ce sont les jambes qui travaillent, et dès qu'une main frappe la surface pour s'aider, l'intervalle est terminé.",
                    "Tangan di atas air dan tetap di sana: kaki yang bekerja; begitu tangan menepuk air, interval selesai.",
                    "Tangan di atas air dan kekal di situ: kaki yang bekerja; sebaik tangan menepuk air, selang itu tamat.",
                    "ยกมือพ้นน้ำและค้างไว้ ขาคือคนทำงาน พอมือตบน้ำเพื่อช่วยพยุงเมื่อไหร่ ถือว่าจบรอบนั้น",
                    "Hai tay giơ khỏi mặt nước và giữ nguyên: chân làm việc; ngay khi một tay đập nước để trợ lực là kết thúc lượt."),
            home=[P(0.50, 0.70, "A",
                    moves=[(0.50, 0.62, 0), (0.50, 0.70, 1)],
                    why={0: "tread", 1: "tread"})],
            markers=[M(0.50, 0.66, "zone")],
            setup=_s("the group spread across the pool in deep water, an arm's length apart, facing the coach",
                     "全组在深水区一字排开，彼此相隔一臂，面向教练",
                     "全組在深水區一字排開，彼此相隔一臂，面向教練"),
            gear=_s("the shaded zone is the deep water the set is done in — out of reach of the wall and the bottom, because holding on is what the drill is training you not to need",
                    "阴影区是做这组练习的深水区——够不到池壁和池底，因为这个练习练的正是不需要借力",
                    "陰影區是做這組練習的深水區——夠不到池壁和池底，因為這個練習練的正是不需要借力"),
            flow=_s("Thirty seconds high with both hands up, thirty seconds easy treading; ten repetitions. Add a ball held overhead for the last three once the set is comfortable.",
                    "双手举高踩水 30 秒、放松踩水 30 秒，做 10 次。这组做得轻松以后，最后 3 次改为双手举球。",
                    "雙手舉高踩水 30 秒、放鬆踩水 30 秒，做 10 次。這組做得輕鬆以後，最後 3 次改為雙手舉球。"),
        ),
        Drill(
            id="wpfit_sprint_lengths", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_WATER,
            name=_t("Sprint lengths", "全场冲刺游", "全場衝刺游", "スプリント往復", "스프린트 랩",
                    "Largos a sprint", "Longueurs en sprint", "Sprint menyusuri kolam",
                    "Pecutan sepanjang kolam", "ว่ายสปรินต์เต็มสระ", "Bơi nước rút hết chiều dài"),
            note=_t("Head up on the first three strokes and the last three: a water polo sprint that puts its face in the water for the finish is a swimmer's sprint, not a player's.",
                    "起游前三划和到边前三划都要抬头：整段把脸埋在水里的冲刺是游泳运动员的冲刺，不是水球运动员的。",
                    "起游前三划和到邊前三划都要抬頭：整段把臉埋在水裡的衝刺是游泳運動員的衝刺，不是水球運動員的。",
                    "最初の3ストロークと最後の3ストロークは顔を上げる：フィニッシュで顔を沈めるスプリントは水泳選手のもので、水球選手のものではない。",
                    "처음 세 스트로크와 마지막 세 스트로크는 고개를 든다: 마무리에서 얼굴을 담그는 스프린트는 수영 선수의 것이지 수구 선수의 것이 아니다.",
                    "Cabeza fuera en las tres primeras brazadas y en las tres últimas: un sprint de waterpolo que mete la cara para terminar es un sprint de nadador, no de jugador.",
                    "Tête haute sur les trois premières et les trois dernières nages : un sprint de water-polo qui plonge le visage à l'arrivée est un sprint de nageur, pas de joueur.",
                    "Kepala di atas air pada tiga kayuhan pertama dan terakhir.",
                    "Kepala di atas air pada tiga kayuhan pertama dan terakhir.",
                    "เงยหน้าในสามจังหวะแรกและสามจังหวะสุดท้าย",
                    "Ngẩng đầu ở ba nhịp đầu và ba nhịp cuối: cú nước rút vùi mặt khi về đích là của vận động viên bơi, không phải của cầu thủ."),
            home=[P(0.50, 0.90, "A",
                    moves=[(0.50, 0.10, 0), (0.50, 0.90, 1)],
                    why={0: "swim", 1: "swim"})],
            setup=_s("the group on one goal line in lanes an arm's length apart; the far goal line is the finish",
                     "全组在一侧门线排开，彼此相隔一臂；对面门线是终点",
                     "全組在一側門線排開，彼此相隔一臂；對面門線是終點"),
            gear=_s("no equipment: the two goal lines are the ends, and every sprint finishes with a hand on the line, not near it",
                    "不需要器材：两条门线就是两端，每次冲刺都要用手摸到线，不是靠近就算",
                    "不需要器材：兩條門線就是兩端，每次衝刺都要用手摸到線，不是靠近就算"),
            flow=_s("Sprint one length, 30 seconds' easy swimming back, and go again; ten lengths, then three minutes and ten more. The last two must be inside a second of the first two.",
                    "冲刺一趟，30 秒放松游回来，接着下一趟；做 10 趟后休息 3 分钟，再做 10 趟。最后两趟和前两趟的时间差不能超过 1 秒。",
                    "衝刺一趟，30 秒放鬆游回來，接著下一趟；做 10 趟後休息 3 分鐘，再做 10 趟。最後兩趟和前兩趟的時間差不能超過 1 秒。"),
        ),
        Drill(
            id="wpfit_lunges", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_WATER, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.60, "A",
                    moves=[(0.50, 0.52, 0), (0.50, 0.60, 1), (0.50, 0.52, 2), (0.50, 0.60, 3)],
                    why={0: "jump", 1: "tread", 2: "jump", 3: "tread"})],
            markers=[M(0.50, 0.56, "zone")],
            setup=_s("the group in deep water facing the coach, far enough apart that nobody lands on anybody",
                     "全组在深水区面向教练排开，彼此距离足够，避免落下时压到别人",
                     "全組在深水區面向教練排開，彼此距離足夠，避免落下時壓到別人"),
            gear=_s("the shaded zone is the deep water the lunges are done in: each one rises from an eggbeater, out of the water to the hips, and sinks back under control",
                    "阴影区是做出水动作的深水区：每一次都从踩水开始，把身体拉出水面到髋部，再有控制地落回",
                    "陰影區是做出水動作的深水區：每一次都從踩水開始，把身體拉出水面到髖部，再有控制地落回"),
            flow=_s("Eight lunges out of the water with the shooting arm up, 90 seconds' rest; four sets. When the hips stop clearing the surface the set is finished.",
                    "举起射门手做 8 次出水动作，休息 90 秒；做 4 组。髋部出不了水面就结束这一组。",
                    "舉起射門手做 8 次出水動作，休息 90 秒；做 4 組。髖部出不了水面就結束這一組。"),
        ),
    ]


# ══ baseball ═════════════════════════════════════════════════════════════
def _baseball():
    return [
        Drill(
            id="bbfit_home_to_first", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, free=True,
            name=_t("Home to first", "本垒到一垒冲刺", "本壘到一壘衝刺", "本塁から一塁へのダッシュ",
                    "홈에서 1루까지 질주", "De home a primera", "Du marbre à la première base",
                    "Home ke base satu", "Home ke base pertama", "วิ่งจากโฮมไปเบสหนึ่ง",
                    "Chạy từ gôn nhà lên chốt một"),
            note=_t("Run through the bag, never at it: the first three steps out of the box and the last three past the base are where the whole time is won or lost.",
                    "跑过垒包，不要跑到垒包为止：出击球区的头三步和过垒的最后三步，决定了整段时间。",
                    "跑過壘包，不要跑到壘包為止：出擊球區的頭三步和過壘的最後三步，決定了整段時間。",
                    "ベースを駆け抜ける、ベースで止まらない：打席を出る最初の3歩とベースを過ぎる最後の3歩で、タイムのすべてが決まる。",
                    "베이스를 밟고 지나쳐 달린다, 베이스에서 멈추지 않는다: 타석을 나서는 첫 세 걸음과 베이스를 지나는 마지막 세 걸음이 기록의 전부다.",
                    "Corre a través de la base, nunca hacia ella: los tres primeros pasos fuera del cajón y los tres últimos pasada la base deciden todo el tiempo.",
                    "Traverse le sac, ne t'arrête pas dessus : les trois premiers pas hors de la boîte et les trois derniers après la base font tout le chrono.",
                    "Lari menembus base, bukan berhenti di base: tiga langkah pertama dan tiga langkah terakhir menentukan waktunya.",
                    "Lari menembusi base, bukan berhenti di base: tiga langkah pertama dan tiga langkah terakhir menentukan masanya.",
                    "วิ่งผ่านเบส ไม่ใช่วิ่งถึงเบสแล้วหยุด สามก้าวแรกออกจากกรอบและสามก้าวสุดท้ายหลังเบสคือทั้งหมดของเวลา",
                    "Chạy vượt qua chốt, đừng chạy tới chốt rồi dừng: ba bước đầu rời ô đánh và ba bước cuối qua chốt quyết định toàn bộ thời gian."),
            home=[P(0.53, 0.89, "A",
                    moves=[(0.68, 0.74, 0), (0.77, 0.65, 1), (0.53, 0.89, 2)],
                    why={0: "sprint", 1: "sprint", 2: "jog"})],
            # The field draws its own bases; a second set on top of them read
            # as four more bags in the infield.
            markers=[M(0.80, 0.62)],
            setup=_s("the batter in the box at home plate, first base occupied by nobody; a cone five metres past the bag in foul ground",
                     "击球员站在本垒打击区，一垒无人；界外区、垒包外五米处放一个锥标",
                     "擊球員站在本壘打擊區，一壘無人；界外區、壘包外五米處放一個錐標"),
            gear=_s("one cone, five metres past first base in foul ground: the timer stops at the bag, the legs stop at the cone, and nobody slows down before either",
                    "只用一个锥标，放在一垒垒包外五米的界外区：计时在垒包停，人要跑到锥标，两者之前都不许减速",
                    "只用一個錐標，放在一壘壘包外五米的界外區：計時在壘包停，人要跑到錐標，兩者之前都不許減速"),
            flow=_s("Six runs each from a swing, timed: 4.3 seconds is average for a right-handed hitter, under 4.1 is a runner. Ninety seconds between runs, and walk back in foul ground.",
                    "每人从挥棒开始跑 6 次并计时：右打者 4.3 秒是平均水平，4.1 秒以内算跑者。每次之间休息 90 秒，沿界外区走回来。",
                    "每人從揮棒開始跑 6 次並計時：右打者 4.3 秒是平均水平，4.1 秒以內算跑者。每次之間休息 90 秒，沿界外區走回來。"),
        ),
        Drill(
            id="bbfit_base_circuit", category="conditioning", minutes=10, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("Around the bases", "绕垒跑", "繞壘跑", "ベースランニング一周", "베이스 한 바퀴",
                    "Vuelta a las bases", "Tour des bases", "Keliling base",
                    "Keliling base", "วิ่งรอบเบส", "Chạy vòng các chốt"),
            note=_t("Hit the inside corner of every bag and lean into the turn — a runner who takes the bases square adds a stride at every one of them.",
                    "每个垒包都踩内侧角，身体往内倾——直角过垒的人，每个垒都多跑一步。",
                    "每個壘包都踩內側角，身體往內傾——直角過壘的人，每個壘都多跑一步。",
                    "各ベースの内側の角を踏み、ターンでは内側に傾く——直角に回る走者は、ベースごとに一歩ずつ損をする。",
                    "모든 베이스의 안쪽 모서리를 밟고 안으로 기울인다 — 직각으로 도는 주자는 베이스마다 한 걸음씩 더 뛴다.",
                    "Pisa la esquina interior de cada base e inclínate en el giro: el que las toma en ángulo recto añade una zancada en cada una.",
                    "Touche le coin intérieur de chaque base et penche-toi dans le virage : celui qui les prend à angle droit ajoute une foulée à chacune.",
                    "Injak sudut dalam tiap base dan condongkan badan di tikungan.",
                    "Pijak sudut dalam setiap base dan condongkan badan pada selekoh.",
                    "เหยียบมุมในของทุกเบสและเอียงตัวเข้าโค้ง",
                    "Đạp góc trong của mỗi chốt và nghiêng người vào cua — ai chạy vuông góc sẽ mất thêm một sải ở từng chốt."),
            home=[P(0.53, 0.89, "A",
                    moves=[(0.68, 0.74, 0), (0.50, 0.56, 1), (0.32, 0.74, 2), (0.50, 0.92, 3)],
                    why={0: "sprint", 1: "sprint", 2: "sprint", 3: "sprint"})],
            # No markers: the diamond's own bases are the four turns.
            markers=[],
            setup=_s("the four bases, a runner at home plate; the rest of the group waits behind the plate",
                     "四个垒包就位，跑者在本垒板，其余人在本垒后方等候",
                     "四個壘包就位，跑者在本壘板，其餘人在本壘後方等候"),
            gear=_s("no equipment: the diamond's own bases are the four turns — the inside corner of each is what the foot touches, and the arc swings out into the grass between them",
                    "不需要器材：场地本身的四个垒包就是四个折返点——脚踩的是每个垒的内侧角，两垒之间的跑动弧线要向外绕出草地",
                    "不需要器材：場地本身的四個壘包就是四個折返點——腳踩的是每個壘的內側角，兩壘之間的跑動弧線要向外繞出草地"),
            flow=_s("One full lap flat out — around 15 seconds — then two minutes' rest while the rest of the group goes; four laps each.",
                    "全力跑完一圈约 15 秒，然后趁其他人跑的时候休息 2 分钟；每人 4 圈。",
                    "全力跑完一圈約 15 秒，然後趁其他人跑的時候休息 2 分鐘；每人 4 圈。"),
        ),
        Drill(
            id="bbfit_first_step", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.40, 0.62, "A",
                    moves=[(0.28, 0.57, 0), (0.40, 0.62, 1), (0.52, 0.57, 2), (0.40, 0.62, 3)],
                    why={0: "sprint", 1: "reset", 2: "sprint", 3: "reset"})],
            markers=[M(0.40, 0.64), M(0.26, 0.55), M(0.54, 0.55)],
            setup=_s("an infielder on his position with a cone either side of him at five metres; the coach stands in front and points",
                     "内野手站在自己的防守位置，左右各五米放一个锥标；教练在前方指方向",
                     "內野手站在自己的防守位置，左右各五米放一個錐標；教練在前方指方向"),
            gear=_s("the middle cone is the fielding position and the two 5 m either side are the balls to his left and right: the first step is a crossover, not a hop, and the glove is down before the cone is reached",
                    "中间锥标是防守站位，两侧锥标各在五米开外，代表左右两边的球：第一步必须是交叉步而不是原地垫步，手套要在到达锥标之前就已经放下去",
                    "中間錐標是防守站位，兩側錐標各在五米開外，代表左右兩邊的球：第一步必須是交叉步而不是原地墊步，手套要在到達錐標之前就已經放下去"),
            flow=_s("Twenty seconds of first steps on the coach's hand, forty seconds' rest; eight repetitions, then swap with the next fielder.",
                    "教练指方向，做 20 秒启动步、休息 40 秒，做 8 次后换下一名内野手。",
                    "教練指方向，做 20 秒啟動步、休息 40 秒，做 8 次後換下一名內野手。"),
        ),
    ]


# ══ sepak takraw ═════════════════════════════════════════════════════════
def _sepak_takraw():
    return [
        Drill(
            id="stfit_jump_series", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, free=True, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.66, "A",
                    moves=[(0.50, 0.58, 0), (0.50, 0.66, 1), (0.50, 0.58, 2), (0.50, 0.66, 3)],
                    why={0: "jump", 1: "reset", 2: "jump", 3: "reset"})],
            markers=[M(0.50, 0.62, "zone")],
            setup=_s("a striker two steps behind the net with the court clear in front of him",
                     "攻手站在网后两步的位置，身前场地清空",
                     "攻手站在網後兩步的位置，身前場地清空"),
            gear=_s("the shaded zone is the take-off and landing area at the net: the jump goes up inside it and comes down inside it — a spike that lands a metre forward has taken the body under the net",
                    "阴影区是网前的起跳和落地区：起跳和落地都要在区内完成——落点往前一米就说明身体已经钻到网下去了",
                    "陰影區是網前的起跳和落地區：起跳和落地都要在區內完成——落點往前一米就說明身體已經鑽到網下去了"),
            flow=_s("Eight take-offs with the full roll-spike action, then two minutes' rest; four sets, and stop the set if a landing is not on two feet.",
                    "带完整倒钩扣球动作的起跳做 8 次，休息 2 分钟；做 4 组，只要有一次不是双脚落地就停止这一组。",
                    "帶完整倒鉤扣球動作的起跳做 8 次，休息 2 分鐘；做 4 組，只要有一次不是雙腳落地就停止這一組。"),
        ),
        Drill(
            id="stfit_court_corners", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_COURT, name=REPEAT_NAME, note=REPEAT_NOTE,
            home=[P(0.50, 0.74, "A",
                    moves=[(0.22, 0.60, 0), (0.50, 0.74, 1), (0.78, 0.60, 2), (0.50, 0.74, 3),
                           (0.22, 0.92, 4), (0.50, 0.74, 5), (0.78, 0.92, 6), (0.50, 0.74, 7)],
                    why={0: "sprint", 1: "reset", 2: "sprint", 3: "reset",
                         4: "sprint", 5: "reset", 6: "sprint", 7: "reset"})],
            markers=[M(0.20, 0.58), M(0.80, 0.58), M(0.20, 0.94), M(0.80, 0.94), M(0.50, 0.76)],
            setup=_s("a cone in the middle of the half and one in each of its four corners; the player starts on the middle one",
                     "本方半场中间一个锥标，四个角各一个；球员站在中间锥标上",
                     "本方半場中間一個錐標，四個角各一個；球員站在中間錐標上"),
            gear=_s("the middle cone is base and the four corners are the points a regu has to cover: reach each with a foot, not a hand, and recover to base",
                    "中间锥标是原点，四个角是一队三人要覆盖的四个点：用脚够到每个点（不是用手），再回到原点",
                    "中間錐標是原點，四個角是一隊三人要覆蓋的四個點：用腳夠到每個點（不是用手），再回到原點"),
            flow=_s("Four corners and back is one round; rest 40 seconds and go again. Six rounds each, then the three players rotate positions.",
                    "四个角各去一次回来算一轮；休息 40 秒再来。每人 6 轮后三人换位。",
                    "四個角各去一次回來算一輪；休息 40 秒再來。每人 6 輪後三人換位。"),
        ),
        Drill(
            id="stfit_ankle_hops", category="conditioning", minutes=6, rel=True,
            purpose=PURPOSE_COURT,
            name=_t("Ankle hops", "踝关节连续弹跳", "踝關節連續彈跳", "アンクルホップ", "발목 호핑",
                    "Saltos de tobillo", "Sauts de cheville", "Lompat pergelangan kaki",
                    "Lompatan buku lali", "กระโดดข้อเท้า", "Bật cổ chân"),
            note=_t("Knees barely bend: this is the ankle, and the ankle is what the second jump of a rally is made of.",
                    "膝盖几乎不弯：练的是踝关节，而一个回合里的第二跳靠的就是踝。",
                    "膝蓋幾乎不彎：練的是踝關節，而一個回合裡的第二跳靠的就是踝。",
                    "膝はほとんど曲げない：これは足首の練習で、ラリー中の2本目のジャンプは足首でできている。",
                    "무릎은 거의 굽히지 않는다: 이것은 발목 훈련이고, 랠리 중 두 번째 점프는 발목으로 만들어진다.",
                    "Las rodillas apenas se doblan: esto es el tobillo, y del tobillo sale el segundo salto de un intercambio.",
                    "Les genoux plient à peine : c'est la cheville qui travaille, et le deuxième saut d'un échange vient de la cheville.",
                    "Lutut nyaris tidak menekuk: ini soal pergelangan kaki, dan lompatan kedua dalam reli berasal dari sana.",
                    "Lutut hampir tidak membengkok: ini soal buku lali, dan lompatan kedua dalam rali datang dari situ.",
                    "เข่าแทบไม่งอ นี่คือข้อเท้า และการกระโดดครั้งที่สองในแต้มหนึ่งมาจากข้อเท้า",
                    "Gối gần như không gập: đây là bài cổ chân, và cú bật thứ hai trong một pha bóng đến từ cổ chân."),
            home=[P(0.50, 0.80, "A",
                    moves=[(0.50, 0.76, 0), (0.50, 0.80, 1), (0.50, 0.76, 2), (0.50, 0.80, 3)],
                    why={0: "hop", 1: "reset", 2: "hop", 3: "reset"})],
            markers=[M(0.44, 0.82), M(0.56, 0.82)],
            setup=_s("the player standing between two cones with room overhead; no ball",
                     "球员站在两个锥标之间，头顶留出空间；不用球",
                     "球員站在兩個錐標之間，頭頂留出空間；不用球"),
            gear=_s("the two cones stand a stride apart (about 60 cm) and mark the spot the feet come back to: every hop lands between them, so a set that drifts forward has stopped being an ankle drill",
                    "两个锥标相距一步（约 60 厘米），标出脚要落回的位置：每次弹跳都落在两者之间；整组往前飘就说明已经不是踝关节练习了",
                    "兩個錐標相距一步（約 60 厘米），標出腳要落回的位置：每次彈跳都落在兩者之間；整組往前飄就說明已經不是踝關節練習了"),
            flow=_s("Twenty hops on the spot, fifteen seconds' rest; six sets. Quiet landings — if the group can be heard from the far court the ankles are not doing the work.",
                    "原地弹跳 20 次、休息 15 秒，做 6 组。落地要轻——对面场地都能听见响，说明用的不是踝关节。",
                    "原地彈跳 20 次、休息 15 秒，做 6 組。落地要輕——對面場地都能聽見響，說明用的不是踝關節。"),
        ),
    ]


# ══ beach tennis and footvolley: the sand pair ═══════════════════════════
def _beach_tennis():
    return [
        Drill(
            id="btfit_sand_sprints", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_SAND, free=True, name=SAND_NAME, note=SAND_NOTE,
            home=[P(0.30, 0.92, "A",
                    moves=[(0.30, 0.58, 0), (0.50, 0.92, 1)],
                    why={0: "sprint", 1: "jog"})],
            markers=[M(0.26, 0.94), M(0.26, 0.56)],
            setup=_s("two cones from the baseline to the net on one side of the court; the group goes one at a time",
                     "球场一侧从底线到网前放两个锥标；全组一人一次轮流出发",
                     "球場一側從底線到網前放兩個錐標；全組一人一次輪流出發"),
            gear=_s("the two cones are the ends of the sprint — the baseline and the net; the jog back is outside the court so the next runner has the lane",
                    "两个锥标是冲刺的两端：底线和网前；慢跑回来要走场外，把跑道让给下一个人",
                    "兩個錐標是衝刺的兩端：底線和網前；慢跑回來要走場外，把跑道讓給下一個人"),
            flow=_s("Sprint the length of the court, jog round and go again inside 30 seconds; ten sprints, then three minutes in the shade.",
                    "沿球场长边冲刺一趟，30 秒内绕回来再出发；做 10 次后到阴凉处休息 3 分钟。",
                    "沿球場長邊衝刺一趟，30 秒內繞回來再出發；做 10 次後到陰涼處休息 3 分鐘。"),
        ),
        Drill(
            id="btfit_sand_lateral", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_SAND, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.50, 0.72, "A",
                    moves=[(0.22, 0.72, 0), (0.50, 0.72, 1), (0.78, 0.72, 2), (0.50, 0.72, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.20, 0.75), M(0.50, 0.75), M(0.78, 0.75)],
            setup=_s("three cones across the middle of the half; the player starts on the middle one with the paddle up",
                     "半场中部横向放三个锥标；球员持拍站在中间锥标上",
                     "半場中部橫向放三個錐標；球員持拍站在中間錐標上"),
            gear=_s("three cones 4 m apart are the width a beach-tennis player covers: shuffle to each, play the volley, and come back — in sand the feet lift, so they lift high rather than dragging",
                    "三个锥标相距 4 米，之间就是沙滩网球要覆盖的宽度：滑到每个锥标做出截击动作再回来——沙地必须把脚抬起来，宁可抬高也不要拖着走",
                    "三個錐標相距 4 米，之間就是沙灘網球要覆蓋的寬度：滑到每個錐標做出截擊動作再回來——沙地必須把腳抬起來，寧可抬高也不要拖著走"),
            flow=_s("Twenty seconds side to side, forty seconds' rest; ten repetitions, then the pair swaps.",
                    "左右移动 20 秒、休息 40 秒，做 10 次后两人互换。",
                    "左右移動 20 秒、休息 40 秒，做 10 次後兩人互換。"),
        ),
        Drill(
            id="btfit_sand_jumps", category="conditioning", minutes=6, rel=True,
            purpose=PURPOSE_SAND, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.68, "A",
                    moves=[(0.50, 0.60, 0), (0.50, 0.68, 1), (0.50, 0.60, 2), (0.50, 0.68, 3)],
                    why={0: "jump", 1: "reset", 2: "jump", 3: "reset"})],
            markers=[M(0.50, 0.64, "zone")],
            setup=_s("the player two steps behind the net with the sand raked flat under him",
                     "球员站在网后两步，脚下的沙耙平",
                     "球員站在網後兩步，腳下的沙耙平"),
            gear=_s("the shaded zone is the patch the jump starts and lands in: in sand the take-off foot sinks, so the run-up is shorter and the arm has to do more",
                    "阴影区是起跳和落地的区域：沙地起跳脚会陷进去，所以助跑更短，手臂要出更多力",
                    "陰影區是起跳和落地的區域：沙地起跳腳會陷進去，所以助跑更短，手臂要出更多力"),
            flow=_s("Six smash jumps with the full swing, two minutes' rest; three sets. Sand is unforgiving — stop the moment a landing is uneven.",
                    "带完整挥拍的扣杀起跳做 6 次，休息 2 分钟；做 3 组。沙地不容出错——落地一旦不稳立刻停止。",
                    "帶完整揮拍的扣殺起跳做 6 次，休息 2 分鐘；做 3 組。沙地不容出錯——落地一旦不穩立刻停止。"),
        ),
    ]


def _footvolley():
    return [
        Drill(
            id="fvfit_sand_sprints", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_SAND, free=True, name=SAND_NAME, note=SAND_NOTE,
            home=[P(0.30, 0.90, "A",
                    moves=[(0.30, 0.56, 0), (0.50, 0.90, 1)],
                    why={0: "sprint", 1: "jog"})],
            markers=[M(0.26, 0.92), M(0.26, 0.54)],
            setup=_s("two cones from the baseline to the net on one side of the court; the group goes one at a time",
                     "球场一侧从底线到网前放两个锥标；全组一人一次轮流出发",
                     "球場一側從底線到網前放兩個錐標；全組一人一次輪流出發"),
            gear=_s("the two cones are the ends of the sprint — the baseline and the net; the jog back is outside the court so the next runner has the lane",
                    "两个锥标是冲刺的两端：底线和网前；慢跑回来走场外，把跑道让给下一个人",
                    "兩個錐標是衝刺的兩端：底線和網前；慢跑回來走場外，把跑道讓給下一個人"),
            flow=_s("Sprint the length, jog round and go again inside 30 seconds; ten sprints, then three minutes in the shade.",
                    "沿场地长边冲刺一趟，30 秒内绕回来再出发；做 10 次后到阴凉处休息 3 分钟。",
                    "沿場地長邊衝刺一趟，30 秒內繞回來再出發；做 10 次後到陰涼處休息 3 分鐘。"),
        ),
        Drill(
            id="fvfit_sand_jumps", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_SAND, name=JUMP_NAME, note=JUMP_NOTE,
            home=[P(0.50, 0.66, "A",
                    moves=[(0.50, 0.58, 0), (0.50, 0.66, 1), (0.50, 0.58, 2), (0.50, 0.66, 3)],
                    why={0: "jump", 1: "reset", 2: "jump", 3: "reset"})],
            markers=[M(0.50, 0.62, "zone")],
            setup=_s("the player two steps behind the net, the sand raked flat, nobody in front",
                     "球员站在网后两步，脚下的沙耙平，前方无人",
                     "球員站在網後兩步，腳下的沙耙平，前方無人"),
            gear=_s("the shaded zone is where the jump starts and lands: footvolley lands on the back and the shoulders as often as on the feet, so the zone has to be clear of everybody",
                    "阴影区是起跳和落地的区域：足排球经常是背部和肩部着地，所以这个区域里不能有别人",
                    "陰影區是起跳和落地的區域：足排球經常是背部和肩部著地，所以這個區域裡不能有別人"),
            flow=_s("Six bicycle-kick take-offs with the full action, two minutes' rest; three sets. Land on the shoulder and roll, never on a straight arm.",
                    "带完整倒钩动作的起跳做 6 次，休息 2 分钟；做 3 组。落地用肩着地顺势滚开，绝不能用直臂撑地。",
                    "帶完整倒鉤動作的起跳做 6 次，休息 2 分鐘；做 3 組。落地用肩著地順勢滾開，絕不能用直臂撐地。"),
        ),
        Drill(
            id="fvfit_sand_lateral", category="conditioning", minutes=8, rel=True,
            purpose=PURPOSE_SAND, name=LATERAL_NAME, note=LATERAL_NOTE,
            home=[P(0.50, 0.74, "A",
                    moves=[(0.22, 0.74, 0), (0.50, 0.74, 1), (0.78, 0.74, 2), (0.50, 0.74, 3)],
                    why={0: "shuffle", 1: "shuffle", 2: "shuffle", 3: "shuffle"})],
            markers=[M(0.20, 0.77), M(0.50, 0.77), M(0.78, 0.77)],
            setup=_s("three cones across the middle of the half; the player starts on the middle one",
                     "半场中部横向放三个锥标；球员站在中间锥标上",
                     "半場中部橫向放三個錐標；球員站在中間錐標上"),
            gear=_s("three cones 4 m apart are the width two players have to cover between them: shuffle to each and back, and every arrival is a chest or thigh control, not a look",
                    "三个锥标相距 4 米，之间就是两人要分担的宽度：滑到每个锥标再回来，每次到位都要做出胸部或大腿停球的动作，不是看一眼就算",
                    "三個錐標相距 4 米，之間就是兩人要分擔的寬度：滑到每個錐標再回來，每次到位都要做出胸部或大腿停球的動作，不是看一眼就算"),
            flow=_s("Twenty seconds side to side, forty seconds' rest; ten repetitions, then the pair swaps.",
                    "左右移动 20 秒、休息 40 秒，做 10 次后两人互换。",
                    "左右移動 20 秒、休息 40 秒，做 10 次後兩人互換。"),
        ),
    ]


FITNESS = {
    "basketball": _basketball,
    "volleyball": _volleyball,
    "badminton": _badminton,
    "tennis": _tennis,
    "pickleball": _pickleball,
    "tableTennis": _table_tennis,
    "handball": _handball,
    "rugby": _rugby,
    "fieldHockey": _field_hockey,
    "waterPolo": _water_polo,
    "baseball": _baseball,
    "sepakTakraw": _sepak_takraw,
    "beachTennis": _beach_tennis,
    "footvolley": _footvolley,
}


def fitness_for(sport: str) -> list[Drill]:
    """The sport's conditioning drills, or none where it has its own."""
    build = FITNESS.get(sport)
    return build() if build else []
