"""Soccer conditioning without the ball: the running a session is built on.

Eight drills a coach runs on fitness days and in pre-season — shuttles,
the agility ladder, hurdle hops, the T-run, the star, interval laps,
sprint-and-stop, the yo-yo. No ball on any of them: the point is the
running, and each one says how many, how long and how much rest.
"""
from .engine import Drill, M, P


def _t(en, zh, zht, ja, ko, es, fr, id_, ms, th, vi):
    return {"en": en, "en-GB": en, "zh-CN": zh, "zh-TW": zht, "ja-JP": ja,
            "ko-KR": ko, "es-ES": es, "fr-FR": fr, "id-ID": id_, "ms-MY": ms,
            "th-TH": th, "vi-VN": vi}


def _s(en, zh, zht):
    return {"en": en, "en-GB": en, "zh-CN": zh, "zh-TW": zht}


PURPOSE = _t(
    "Fitness without the ball: sprinting, changing direction and repeating it tired — the running a match asks for, and the last ten minutes are decided by who still has it.",
    "无球体能：冲刺、变向、疲劳下重复——比赛要求的跑动能力，最后十分钟由谁还跑得动决定。",
    "無球體能：衝刺、變向、疲勞下重複——比賽要求的跑動能力，最後十分鐘由誰還跑得動決定。",
    "ボールなしのフィジカル：ダッシュ、方向転換、疲れた状態での反復——試合が求める走力で、最後の10分はまだ走れる者が決める。",
    "볼 없는 체력: 질주, 방향 전환, 지친 상태의 반복 — 경기가 요구하는 달리기이며, 마지막 10분은 아직 뛸 수 있는 쪽이 정한다.",
    "Físico sin balón: esprintar, cambiar de dirección y repetirlo cansado; es la carrera que pide un partido, y los últimos diez minutos los decide quien aún la tiene.",
    "Physique sans ballon : sprinter, changer de direction, répéter fatigué — la course qu'un match exige, et les dix dernières minutes reviennent à qui en a encore.",
    "Fisik tanpa bola: sprint, ganti arah, mengulanginya saat lelah — lari yang diminta pertandingan.",
    "Fizikal tanpa bola: pecut, tukar arah, ulang ketika penat — larian yang dituntut perlawanan.",
    "ฟิตเนสไร้บอล: สปรินต์ เปลี่ยนทิศ และทำซ้ำตอนเหนื่อย คือการวิ่งที่เกมต้องการ",
    "Thể lực không bóng: nước rút, đổi hướng và lặp lại khi mệt — sức chạy trận đấu đòi hỏi, và mười phút cuối thuộc về bên còn chạy được.")


def fitness_family() -> list[Drill]:
    out = []

    # ── 5-10-15 shuttle ─────────────────────────────────────────────────
    out.append(Drill(
        id="fit_shuttle_5_10_15", category="conditioning", purpose=PURPOSE, minutes=10, rel=True,
        free=True,
        name=_t("Shuttle 5-10-15", "折返跑 5-10-15 米", "折返跑 5-10-15 米",
                "シャトルラン 5-10-15", "셔틀런 5-10-15", "Ida y vuelta 5-10-15",
                "Navettes 5-10-15", "Lari bolak-balik 5-10-15", "Lari ulang-alik 5-10-15",
                "วิ่งกลับตัว 5-10-15", "Chạy con thoi 5-10-15"),
        note=_t("Touch the line with the hand, not the foot, and push off the outside leg on every turn — the turn is where the seconds go.",
                "手摸线，不是脚踩线；每次折返用外侧腿蹬出——时间都丢在转身上。",
                "手摸線，不是腳踩線；每次折返用外側腿蹬出——時間都丟在轉身上。",
                "足ではなく手でラインに触れ、ターンは外側の脚で蹴る——タイムはターンで失われる。",
                "발이 아니라 손으로 선을 짚고, 돌 때마다 바깥 다리로 밀어낸다 — 시간은 턴에서 새어 나간다.",
                "Toca la línea con la mano, no con el pie, y empuja con la pierna exterior en cada giro: ahí se van los segundos.",
                "Touche la ligne de la main, pas du pied, et pousse sur la jambe extérieure à chaque demi-tour : c'est là que partent les secondes.",
                "Sentuh garis dengan tangan, bukan kaki, dan dorong dengan kaki luar di setiap putaran.",
                "Sentuh garisan dengan tangan, bukan kaki, dan tolak dengan kaki luar pada setiap pusingan.",
                "แตะเส้นด้วยมือไม่ใช่เท้า และดันด้วยขาด้านนอกทุกครั้งที่กลับตัว",
                "Chạm vạch bằng tay, không phải chân, và đạp bằng chân ngoài mỗi lần quay — thời gian mất ở chỗ quay."),
        home=[P(0.34, 0.80, "A",
                moves=[(0.34, 0.752, 0), (0.34, 0.80, 1), (0.34, 0.705, 2), (0.34, 0.80, 3),
                       (0.34, 0.657, 4), (0.34, 0.80, 5)],
                why={0: "line_5", 1: "turn_back", 2: "line_10", 3: "turn_back",
                     4: "line_15", 5: "turn_back"})],
        markers=[M(0.28, 0.80), M(0.28, 0.752), M(0.28, 0.705), M(0.28, 0.657)],
        setup=_s("four cones in a line 5 m apart, the first one the start; the runner starts on it",
                 "四个锥标排成一列，间隔 5 米，第一个是起点，跑者站在起点上",
                 "四個錐標排成一列，間隔 5 米，第一個是起點，跑者站在起點上"),
        gear=_s("the four cones are the start and the 5, 10 and 15 m lines; each is touched and the runner comes back to the start",
                "四个锥标分别是起点和 5、10、15 米线，每到一个锥标摸线后跑回起点",
                "四個錐標分別是起點和 5、10、15 米線，每到一個錐標摸線後跑回起點"),
        flow=_s("One shuttle is 5 m and back, 10 m and back, 15 m and back; rest 45 seconds and go again. Six shuttles a set, two sets, three minutes between sets.",
                "一趟 = 5 米折返、10 米折返、15 米折返；休息 45 秒再跑。6 趟一组，做 2 组，组间休息 3 分钟。",
                "一趟 = 5 米折返、10 米折返、15 米折返；休息 45 秒再跑。6 趟一組，做 2 組，組間休息 3 分鐘。"),
    ))

    # ── agility ladder ──────────────────────────────────────────────────
    out.append(Drill(
        id="fit_agility_ladder", category="conditioning", purpose=PURPOSE, minutes=8, rel=True,
        name=_t("Agility ladder", "敏捷梯", "敏捷梯", "ラダートレーニング", "래더 훈련",
                "Escalera de agilidad", "Échelle de rythme", "Tangga kelincahan",
                "Tangga ketangkasan", "บันไดลิง", "Thang dây"),
        note=_t("Light and fast on the balls of the feet, arms driving, eyes up — the ladder is over in three seconds and the sprint after it is what it was for.",
                "前脚掌轻快落地，摆臂，眼睛看前方——梯子三秒就过完，之后那段冲刺才是目的。",
                "前腳掌輕快落地，擺臂，眼睛看前方——梯子三秒就過完，之後那段衝刺才是目的。",
                "母指球で軽く速く、腕を振り、目線は前——ラダーは3秒で終わる。その後のダッシュが目的だ。",
                "앞발로 가볍고 빠르게, 팔을 흔들고, 시선은 앞으로 — 래더는 3초면 끝나고 그 뒤의 질주가 목적이다.",
                "Ligero y rápido sobre la punta de los pies, brazos activos, vista al frente: la escalera dura tres segundos y el sprint de después es lo que importa.",
                "Léger et vif sur l'avant du pied, bras actifs, regard devant : l'échelle dure trois secondes, le sprint qui suit est le vrai objectif.",
                "Ringan dan cepat di ujung kaki, lengan aktif, mata ke depan — tangga selesai tiga detik, sprint sesudahnya yang penting.",
                "Ringan dan pantas di hujung kaki, lengan aktif, mata ke hadapan — tangga selesai tiga saat, pecutan selepasnya yang penting.",
                "เบาและเร็วบนปลายเท้า แกว่งแขน มองไปข้างหน้า บันไดจบในสามวินาที สปรินต์หลังจากนั้นคือเป้าหมาย",
                "Nhẹ và nhanh trên mũi chân, đánh tay, mắt nhìn trước — thang chỉ ba giây, cú nước rút sau đó mới là mục đích."),
        home=[P(0.50, 0.78, "A",
                moves=[(0.50, 0.66, 0), (0.50, 0.54, 1), (0.60, 0.66, 2), (0.50, 0.78, 3)],
                why={0: "ladder", 1: "sprint", 2: "jog", 3: "jog"})],
        markers=[M(0.50, 0.72, "ladder"), M(0.44, 0.54)],
        setup=_s("an agility ladder on the ground with a cone 12 m past its far end; the runner starts a stride before the ladder",
                 "地上放一条敏捷梯，梯子远端外 12 米放一个锥标，跑者站在梯子前一步",
                 "地上放一條敏捷梯，梯子遠端外 12 米放一個錐標，跑者站在梯子前一步"),
        gear=_s("the ladder is stepped through in four patterns — one foot per rung, two feet per rung, in-and-out, and sideways; the cone is the sprint target after the last rung. Jog back round the outside, never back through it",
                "敏捷梯用四种步法过：每格一步、每格两步、进出步、侧向步；锥标是过完最后一格后冲刺的目标。回来从梯子外侧绕，不要穿回去",
                "敏捷梯用四種步法過：每格一步、每格兩步、進出步、側向步；錐標是過完最後一格後衝刺的目標。回來從梯子外側繞，不要穿回去"),
        flow=_s("Through the ladder, sprint to the cone, jog back round to the start and the next player goes at once; each pattern six times, four patterns.",
                "过梯、冲到锥标、绕回起点，下一人马上出发；每种步法做 6 次，共 4 种步法。",
                "過梯、衝到錐標、繞回起點，下一人馬上出發；每種步法做 6 次，共 4 種步法。"),
    ))

    # ── hurdle hops ─────────────────────────────────────────────────────
    out.append(Drill(
        id="fit_hurdle_hops", category="conditioning", purpose=PURPOSE, minutes=8, rel=True,
        name=_t("Hurdle hops", "栏架跳跃", "欄架跳躍", "ハードルジャンプ", "허들 점프",
                "Saltos de valla", "Sauts de haies", "Lompat gawang", "Lompat pagar",
                "กระโดดรั้ว", "Bật rào"),
        note=_t("Land soft and leave fast — the less time the feet spend on the ground between hurdles, the more the drill gives you.",
                "落地轻、离地快——两个栏架之间脚在地上停的时间越短，练到的越多。",
                "落地輕、離地快——兩個欄架之間腳在地上停的時間越短，練到的越多。",
                "柔らかく着地して素早く離れる——ハードル間で足が地面にいる時間が短いほど効く。",
                "부드럽게 착지하고 빠르게 떠난다 — 허들 사이에서 발이 땅에 머무는 시간이 짧을수록 효과가 크다.",
                "Aterriza suave y sal rápido: cuanto menos tiempo pasen los pies en el suelo entre vallas, más rinde el ejercicio.",
                "Atterris souple et repars vite : moins les pieds restent au sol entre les haies, plus l'exercice paie.",
                "Mendarat lembut, pergi cepat — makin singkat kaki di tanah di antara gawang, makin besar hasilnya.",
                "Mendarat lembut, pergi pantas — makin singkat kaki di tanah antara pagar, makin besar hasilnya.",
                "ลงพื้นเบา ออกตัวเร็ว ยิ่งเท้าอยู่บนพื้นระหว่างรั้วน้อย ยิ่งได้ผล",
                "Tiếp đất nhẹ, rời đất nhanh — chân ở mặt đất giữa các rào càng ít, bài tập càng hiệu quả."),
        home=[P(0.50, 0.80, "A",
                moves=[(0.50, 0.745, 0), (0.50, 0.695, 1), (0.50, 0.645, 2), (0.50, 0.595, 3),
                       (0.50, 0.48, 4), (0.60, 0.64, 5), (0.50, 0.80, 6)],
                why={0: "hop", 1: "hop", 2: "hop", 3: "hop", 4: "sprint", 5: "jog", 6: "jog"})],
        # Spaced wider than the metre the text says: a hurdle sprite is a
        # token tall, and four of them a metre apart drew as one.
        markers=[M(0.50, 0.77, "hurdle"), M(0.50, 0.72, "hurdle"),
                 M(0.50, 0.67, "hurdle"), M(0.50, 0.62, "hurdle"), M(0.44, 0.48)],
        setup=_s("four low hurdles in a line a metre apart, a cone 12 m past the last one; the runner starts a stride before the first",
                 "四个小栏架排成一列、间隔 1 米，最后一个栏架外 12 米放一个锥标，跑者站在第一个栏架前一步",
                 "四個小欄架排成一列、間隔 1 米，最後一個欄架外 12 米放一個錐標，跑者站在第一個欄架前一步"),
        gear=_s("the four hurdles are hopped in turn without a stop between them; the cone is the sprint target after the last one. Jog back round the outside of the hurdles",
                "四个栏架依次跳过，中间不停顿；锥标是跳完最后一个后冲刺的目标。回来从栏架外侧绕",
                "四個欄架依次跳過，中間不停頓；錐標是跳完最後一個後衝刺的目標。回來從欄架外側繞"),
        flow=_s("Four hops, sprint to the cone, jog back round to the start and the next player goes; eight runs each, two sets, rest two minutes between sets.",
                "跳四个栏、冲到锥标、绕回起点，下一人出发；每人 8 次一组，做 2 组，组间休息 2 分钟。",
                "跳四個欄、衝到錐標、繞回起點，下一人出發；每人 8 次一組，做 2 組，組間休息 2 分鐘。"),
    ))

    # ── T-run ───────────────────────────────────────────────────────────
    out.append(Drill(
        id="fit_t_run", category="conditioning", purpose=PURPOSE, minutes=8, rel=True, free=True,
        name=_t("T-run", "T 形变向跑", "T 形變向跑", "Tドリル", "T-런",
                "Prueba en T", "Parcours en T", "Lari T", "Larian T", "วิ่งรูปตัว T", "Chạy chữ T"),
        note=_t("Sprint, shuffle, shuffle, backpedal: keep the hips low and face forward the whole way — never turn to look where you are going.",
                "冲刺、侧滑、侧滑、后退跑：全程重心压低、面朝前方——不要转身看要去的地方。",
                "衝刺、側滑、側滑、後退跑：全程重心壓低、面朝前方——不要轉身看要去的地方。",
                "ダッシュ、サイドステップ、サイドステップ、バックペダル：腰を低く、常に前を向く——行き先を振り返らない。",
                "질주, 사이드 스텝, 사이드 스텝, 백페달: 내내 엉덩이를 낮추고 앞을 본다 — 가는 방향으로 몸을 돌리지 않는다.",
                "Sprint, lateral, lateral, atrás: caderas bajas y mirada al frente todo el rato; nunca gires para mirar adónde vas.",
                "Sprint, pas chassés, pas chassés, course arrière : hanches basses, regard devant tout du long — ne te retourne jamais.",
                "Sprint, geser, geser, lari mundur: pinggul rendah dan menghadap ke depan sepanjang jalan.",
                "Pecut, gerak sisi, gerak sisi, lari ke belakang: pinggul rendah dan menghadap ke hadapan sepanjang masa.",
                "สปรินต์ สไลด์ สไลด์ ถอยหลัง สะโพกต่ำและหันหน้าไปข้างหน้าตลอด",
                "Nước rút, trượt ngang, trượt ngang, chạy lùi: hạ thấp hông và luôn hướng mặt về trước — không bao giờ quay người nhìn."),
        home=[P(0.50, 0.79, "A",
                moves=[(0.50, 0.72, 0), (0.41, 0.72, 1), (0.59, 0.72, 2), (0.50, 0.72, 3), (0.50, 0.79, 4)],
                why={0: "sprint", 1: "shuffle", 2: "shuffle", 3: "shuffle", 4: "backpedal"})],
        markers=[M(0.50, 0.81), M(0.50, 0.69), M(0.40, 0.69), M(0.60, 0.69)],
        setup=_s("four cones in a T: the start at the foot, a cone 10 m ahead and one 5 m either side of it; the runner starts on the foot",
                 "四个锥标摆成 T 形：起点在下端，前方 10 米一个，它左右各 5 米各一个，跑者站在起点",
                 "四個錐標擺成 T 形：起點在下端，前方 10 米一個，它左右各 5 米各一個，跑者站在起點"),
        gear=_s("the cones are the four points of the T: sprint to the top, shuffle to the left, across to the right, back to the middle, backpedal to the start",
                "四个锥标是 T 的四个点：冲到顶端，侧滑到左边，再滑到右边，回到中间，后退跑回起点",
                "四個錐標是 T 的四個點：衝到頂端，側滑到左邊，再滑到右邊，回到中間，後退跑回起點"),
        flow=_s("One run, then straight to the back of the line; the next goes as soon as the start cone is clear. Six runs each, and time the last two.",
                "跑完一趟直接排到队尾，起点一空下一人就出发；每人 6 趟，最后两趟计时。",
                "跑完一趟直接排到隊尾，起點一空下一人就出發；每人 6 趟，最後兩趟計時。"),
    ))

    # ── star run ────────────────────────────────────────────────────────
    out.append(Drill(
        id="fit_star_run", category="conditioning", purpose=PURPOSE, minutes=8, rel=True,
        name=_t("Star run", "星形变向跑", "星形變向跑", "スタードリル", "스타 런",
                "Estrella de cambios de dirección", "Étoile", "Lari bintang", "Larian bintang",
                "วิ่งรูปดาว", "Chạy hình sao"),
        note=_t("Every trip out is a sprint and every trip back is the turn that matters: plant, drop the hips, and be facing the centre before the first step back.",
                "每次出去都是冲刺，每次回来练的是转身：蹬地、压低重心，第一步回来之前已经面朝中心。",
                "每次出去都是衝刺，每次回來練的是轉身：蹬地、壓低重心，第一步回來之前已經面朝中心。",
                "外へは毎回ダッシュ、戻りはターンが本題：踏み込み、腰を落とし、最初の一歩の前に中心を向く。",
                "나갈 때는 매번 질주, 돌아올 때는 턴이 핵심: 디디고, 엉덩이를 낮추고, 첫 걸음 전에 이미 중심을 향한다.",
                "Cada ida es un sprint y cada vuelta es el giro que importa: apoya, baja las caderas y mira al centro antes del primer paso de vuelta.",
                "Chaque aller est un sprint, chaque retour est le pivot qui compte : appui, hanches basses, face au centre avant le premier pas.",
                "Setiap pergi adalah sprint, setiap kembali adalah putaran yang penting: tumpu, rendahkan pinggul, hadap pusat sebelum langkah pertama.",
                "Setiap pergi ialah pecutan, setiap kembali ialah pusingan yang penting: tumpu, rendahkan pinggul, hadap pusat sebelum langkah pertama.",
                "ทุกเที่ยวออกคือสปรินต์ ทุกเที่ยวกลับคือการหมุนตัวที่สำคัญ",
                "Mỗi lượt ra là nước rút, mỗi lượt về là cú xoay quan trọng: dậm chân, hạ hông, hướng về tâm trước bước đầu tiên."),
        home=[P(0.50, 0.70, "A",
                moves=[(0.50, 0.62, 0), (0.50, 0.70, 1), (0.58, 0.70, 2), (0.50, 0.70, 3),
                       (0.50, 0.78, 4), (0.50, 0.70, 5), (0.42, 0.70, 6), (0.50, 0.70, 7)],
                why={0: "sprint", 1: "turn_back", 2: "sprint", 3: "turn_back",
                     4: "sprint", 5: "turn_back", 6: "sprint", 7: "turn_back"})],
        markers=[M(0.50, 0.70), M(0.50, 0.60), M(0.60, 0.70), M(0.50, 0.80), M(0.40, 0.70)],
        setup=_s("a centre cone with four cones 8 m out from it, one in each direction; the runner starts on the centre",
                 "中心一个锥标，四周各 8 米各放一个锥标（前后左右），跑者站在中心",
                 "中心一個錐標，四周各 8 米各放一個錐標（前後左右），跑者站在中心"),
        gear=_s("the centre cone is base; the four outer cones are touched in turn — ahead, right, behind, left — coming back to base after each",
                "中心锥标是原点，四个外圈锥标按前、右、后、左的顺序依次摸到，每次都回到原点",
                "中心錐標是原點，四個外圈錐標按前、右、後、左的順序依次摸到，每次都回到原點"),
        flow=_s("Four points and back is one star; rest 40 seconds and go again. Five stars a set, two sets, and reverse the order in the second.",
                "四个点各去一次回来算一颗星；休息 40 秒再来。5 颗星一组，做 2 组，第二组反方向。",
                "四個點各去一次回來算一顆星；休息 40 秒再來。5 顆星一組，做 2 組，第二組反方向。"),
    ))

    # ── interval laps ───────────────────────────────────────────────────
    out.append(Drill(
        id="fit_interval_laps", category="conditioning", purpose=PURPOSE, minutes=15, rel=True,
        name=_t("Interval laps", "间歇跑 绕场", "間歇跑 繞場", "インターバル走", "인터벌 러닝",
                "Vueltas por intervalos", "Tours en intervalles", "Lari interval", "Larian selang",
                "วิ่งอินเทอร์วัลรอบสนาม", "Chạy vòng ngắt quãng"),
        note=_t("The hard minutes should feel like the last ten of a match, the easy ones like walking to a throw-in; if the easy ones are not easy, the hard ones were not hard.",
                "快的一段要像比赛最后十分钟，慢的一段要像走去发界外球；如果慢的不慢，说明快的没快。",
                "快的一段要像比賽最後十分鐘，慢的一段要像走去發界外球；如果慢的不慢，說明快的沒快。",
                "きつい区間は試合の最後の10分、楽な区間はスローインへ歩く感覚で。楽な区間が楽でなければ、きつい区間がきつくなかった。",
                "힘든 구간은 경기 마지막 10분처럼, 쉬운 구간은 스로인하러 걸어가듯이. 쉬운 구간이 쉽지 않다면 힘든 구간이 힘들지 않았던 것이다.",
                "Los tramos duros deben sentirse como los últimos diez minutos de un partido y los suaves como caminar a un saque de banda; si los suaves no son suaves, los duros no fueron duros.",
                "Les portions dures doivent ressembler aux dix dernières minutes d'un match, les faciles à une marche vers une touche ; si les faciles ne sont pas faciles, les dures ne l'étaient pas.",
                "Bagian keras terasa seperti sepuluh menit terakhir pertandingan, bagian ringan seperti berjalan ke lemparan ke dalam.",
                "Bahagian keras terasa seperti sepuluh minit terakhir perlawanan, bahagian ringan seperti berjalan ke lontaran ke dalam.",
                "ช่วงหนักต้องเหมือนสิบนาทีสุดท้ายของเกม ช่วงเบาเหมือนเดินไปทุ่มบอล",
                "Phần nặng phải như mười phút cuối trận, phần nhẹ như đi bộ ra ném biên; nếu phần nhẹ không nhẹ thì phần nặng chưa nặng."),
        home=[P(0.26, 0.80, "A",
                moves=[(0.26, 0.22, 0), (0.74, 0.22, 1), (0.74, 0.80, 2), (0.26, 0.80, 3)],
                why={0: "sprint", 1: "jog", 2: "sprint", 3: "jog"})],
        markers=[M(0.22, 0.82), M(0.22, 0.20), M(0.78, 0.20), M(0.78, 0.82)],
        setup=_s("four cones marking a rectangle about 60 m long and 30 m wide, between the two boxes; the group starts at one corner",
                 "四个锥标标出一个约 60 米长、30 米宽的长方形，在两个禁区之间；全组从一个角出发",
                 "四個錐標標出一個約 60 米長、30 米寬的長方形，在兩個禁區之間；全組從一個角出發"),
        gear=_s("the four cones are the corners of the lap: the long sides are run hard, the short sides jogged",
                "四个锥标是绕圈的四个角：长边快跑，短边慢跑",
                "四個錐標是繞圈的四個角：長邊快跑，短邊慢跑"),
        flow=_s("Long side hard, short side easy, round and round without stopping; twelve minutes, then three minutes' walk, then eight more. Hard means you could not hold a conversation.",
                "长边快、短边慢，绕圈不停；跑 12 分钟，走 3 分钟，再跑 8 分钟。快的标准是说不出完整句子。",
                "長邊快、短邊慢，繞圈不停；跑 12 分鐘，走 3 分鐘，再跑 8 分鐘。快的標準是說不出完整句子。"),
    ))

    # ── sprint and stop ─────────────────────────────────────────────────
    out.append(Drill(
        id="fit_sprint_stop", category="conditioning", purpose=PURPOSE, minutes=8, rel=True,
        name=_t("Sprint and stop", "冲刺急停", "衝刺急停", "スプリント＆ストップ", "스프린트 앤 스톱",
                "Sprint y frenada", "Sprint et arrêt", "Sprint dan berhenti", "Pecut dan berhenti",
                "สปรินต์แล้วหยุด", "Nước rút và dừng"),
        note=_t("The stop is the exercise: three short steps, knees bent, weight back, feet still inside the zone. A stop that skids past the cones is a hamstring waiting to happen.",
                "急停才是练习的内容：三个小步、屈膝、重心靠后，脚停在区域内。滑出锥标的急停是在等着拉伤腘绳肌。",
                "急停才是練習的內容：三個小步、屈膝、重心靠後，腳停在區域內。滑出錐標的急停是在等著拉傷膕繩肌。",
                "止まることが練習：小さく3歩、膝を曲げ、重心を後ろに、足はゾーン内で止める。コーンを滑り抜ける止まり方はハムストリングの故障予備軍だ。",
                "멈춤이 곧 훈련이다: 짧은 세 걸음, 무릎 굽히고, 체중 뒤로, 발은 구역 안에서 멈춘다. 콘을 미끄러져 지나치는 멈춤은 햄스트링 부상의 예고다.",
                "La frenada es el ejercicio: tres pasos cortos, rodillas flexionadas, peso atrás, pies dentro de la zona. Una frenada que patina más allá de los conos es una lesión de isquios esperando.",
                "L'arrêt est l'exercice : trois petits pas, genoux fléchis, poids en arrière, pieds dans la zone. Un arrêt qui dérape au-delà des plots, c'est un ischio qui attend.",
                "Berhentinya adalah latihannya: tiga langkah pendek, lutut ditekuk, berat ke belakang, kaki tetap di zona.",
                "Berhenti itulah latihannya: tiga langkah pendek, lutut dibengkokkan, berat ke belakang, kaki kekal di zon.",
                "การหยุดคือแบบฝึก สามก้าวสั้น ย่อเข่า น้ำหนักไปหลัง เท้าหยุดในโซน",
                "Cú dừng mới là bài tập: ba bước ngắn, gối khuỵu, trọng tâm lùi, chân dừng trong vùng. Dừng trượt qua cọc là gân kheo đang chờ chấn thương."),
        home=[P(0.50, 0.80, "A",
                moves=[(0.50, 0.615, 0), (0.50, 0.575, 1), (0.50, 0.80, 2)],
                why={0: "sprint", 1: "decel", 2: "jog"})],
        markers=[M(0.44, 0.80), M(0.44, 0.60), M(0.56, 0.60), M(0.44, 0.55), M(0.56, 0.55)],
        setup=_s("a start cone, and 20 m ahead of it a 5 m stopping zone marked by four cones; the runner starts on the start cone",
                 "一个起点锥标，前方 20 米处用四个锥标围出一个 5 米长的急停区，跑者站在起点",
                 "一個起點錐標，前方 20 米處用四個錐標圍出一個 5 米長的急停區，跑者站在起點"),
        gear=_s("the single cone is the start; the four cones mark the zone the runner has to be stopped inside — not before it, not past it",
                "单独的锥标是起点；四个锥标围出的区域是必须在里面停住的地方——不能提前停，也不能冲出去",
                "單獨的錐標是起點；四個錐標圍出的區域是必須在裡面停住的地方——不能提前停，也不能衝出去"),
        flow=_s("Sprint, stop in the zone, jog back to the start and the next player goes; eight each, then the zone moves 5 m closer for a second set of eight.",
                "冲刺、在区域内停住、慢跑回起点，下一人出发；每人 8 次，然后把急停区往前挪 5 米再做一组 8 次。",
                "衝刺、在區域內停住、慢跑回起點，下一人出發；每人 8 次，然後把急停區往前挪 5 米再做一組 8 次。"),
    ))

    # ── yo-yo ───────────────────────────────────────────────────────────
    out.append(Drill(
        id="fit_yoyo", category="conditioning", purpose=PURPOSE, minutes=15, rel=True,
        name=_t("Yo-yo intermittent runs", "Yo-Yo 间歇往返跑", "Yo-Yo 間歇往返跑", "ヨーヨーテスト形式の間欠走",
                "요요 간헐 달리기", "Yo-yo intermitente", "Yo-yo intermittent", "Lari yo-yo", "Larian yo-yo",
                "วิ่งโยโย่", "Chạy yo-yo"),
        note=_t("Arrive on the beep, not before it — running early is wasted, and the ten seconds of jogging are part of the drill, not a break from it.",
                "踩着哨声到线，别提前——早到的都是白跑；十秒慢跑是练习的一部分，不是休息。",
                "踩著哨聲到線，別提前——早到的都是白跑；十秒慢跑是練習的一部分，不是休息。",
                "ビープに合わせて到着し、早すぎない——早く走るのは無駄。10秒の歩きはドリルの一部で休憩ではない。",
                "신호에 맞춰 도착하고 앞서지 않는다 — 일찍 달리는 것은 낭비. 10초 걷기는 훈련의 일부지 휴식이 아니다.",
                "Llega con el pitido, no antes: correr adelantado es correr de más, y los diez segundos caminando son parte del ejercicio, no un descanso.",
                "Arrive sur le bip, pas avant : courir en avance ne sert à rien, et les dix secondes de marche font partie de l'exercice, pas de la pause.",
                "Tiba tepat pada bunyi bip, bukan sebelumnya; sepuluh detik berjalan adalah bagian dari latihan.",
                "Tiba tepat pada bunyi bip, bukan sebelumnya; sepuluh saat berjalan ialah sebahagian daripada latihan.",
                "ถึงเส้นตามเสียงบี๊บ อย่าถึงก่อน สิบวินาทีที่เดินคือส่วนหนึ่งของแบบฝึก",
                "Đến vạch đúng tiếng bíp, không đến sớm — chạy sớm là phí sức; mười giây đi bộ là một phần của bài, không phải nghỉ."),
        home=[P(0.50, 0.80, "A",
                moves=[(0.50, 0.62, 0), (0.50, 0.80, 1), (0.50, 0.845, 2), (0.50, 0.80, 3)],
                why={0: "sprint", 1: "turn_back", 2: "jog", 3: "jog"})],
        markers=[M(0.42, 0.80), M(0.58, 0.80), M(0.42, 0.61), M(0.58, 0.61), M(0.42, 0.85), M(0.58, 0.85)],
        setup=_s("three pairs of cones: the start line, a turn line 20 m ahead, and a recovery line 5 m behind the start; the runner starts on the start line",
                 "三对锥标：起点线、前方 20 米的折返线、起点后方 5 米的恢复线，跑者站在起点线上",
                 "三對錐標：起點線、前方 20 米的折返線、起點後方 5 米的恢復線，跑者站在起點線上"),
        gear=_s("the middle pair is the start, the far pair the 20 m turn, the near pair the 5 m recovery line; out and back on the beep, then jog to the near pair and back — the ten seconds of active recovery — and go again",
                "中间一对是起点，远端一对是 20 米折返线，近端一对是 5 米恢复线；听哨出发跑到折返线再回来，然后慢跑到恢复线再回起点——这是 10 秒的积极恢复——接着下一趟",
                "中間一對是起點，遠端一對是 20 米折返線，近端一對是 5 米恢復線；聽哨出發跑到折返線再回來，然後慢跑到恢復線再回起點——這是 10 秒的積極恢復——接著下一趟"),
        flow=_s("Out and back to the beep, ten seconds' jog round the recovery cones, and again; the beeps get faster every level. Stop the first time you miss the line twice in a row, and note the level.",
                "听哨往返一次，绕恢复锥标慢跑 10 秒，再来；哨声每一级越来越快。连续两次没赶上线就停下，记下到达的级别。",
                "聽哨往返一次，繞恢復錐標慢跑 10 秒，再來；哨聲每一級越來越快。連續兩次沒趕上線就停下，記下到達的級別。"),
    ))
    return out
